/**
 * SelectCareOS™ Documentation API Routes
 * PDF Generation & Document Download
 * 
 * Generated by: Dr. Sherif Akram Metwalli, M.Sc.
 * Powered by: German Select Medical Tourism
 */

import { Hono } from 'hono';

const docsRouter = new Hono();

// Document metadata
const DOCUMENT_INFO = {
  author: 'Dr. Sherif Akram Metwalli, M.Sc.',
  company: 'German Select Medical Tourism',
  website: 'www.germanselect.org',
  email: 'info@germanselect.org',
  version: '1.0',
  date: new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' }),
  copyright: `© ${new Date().getFullYear()} German Select. All Rights Reserved.`
};

// Professional PDF Header/Footer template
const PDF_STYLES = `
<style>
  @import url('https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800&display=swap');
  
  * {
    font-family: 'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
    box-sizing: border-box;
  }
  
  body {
    color: #001F3F;
    line-height: 1.6;
    font-size: 11pt;
    margin: 0;
    padding: 40px;
  }
  
  /* Cover Page */
  .cover-page {
    page-break-after: always;
    height: 100vh;
    display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;
    text-align: center;
    background: linear-gradient(135deg, #001F3F 0%, #003366 100%);
    color: white;
    margin: -40px;
    padding: 60px;
  }
  
  .cover-logo {
    font-size: 42pt;
    font-weight: 800;
    margin-bottom: 16px;
  }
  
  .cover-logo span {
    color: #D4A843;
  }
  
  .cover-title {
    font-size: 28pt;
    font-weight: 700;
    color: #D4A843;
    margin: 24px 0 8px;
  }
  
  .cover-subtitle {
    font-size: 14pt;
    color: rgba(255, 255, 255, 0.8);
    margin-bottom: 60px;
  }
  
  .cover-meta {
    margin-top: auto;
    font-size: 10pt;
    color: rgba(255, 255, 255, 0.7);
  }
  
  .cover-meta strong {
    color: #D4A843;
  }
  
  .cover-meta .divider {
    margin: 12px 0;
    height: 1px;
    width: 100px;
    background: rgba(212, 168, 67, 0.5);
  }
  
  .cover-badge {
    display: inline-block;
    background: rgba(212, 168, 67, 0.2);
    border: 1px solid rgba(212, 168, 67, 0.4);
    padding: 8px 20px;
    border-radius: 30px;
    font-size: 10pt;
    font-weight: 600;
    color: #D4A843;
    text-transform: uppercase;
    letter-spacing: 2px;
    margin-bottom: 40px;
  }
  
  /* Document Header */
  .doc-header {
    border-bottom: 2px solid #D4A843;
    padding-bottom: 12px;
    margin-bottom: 24px;
    display: flex;
    justify-content: space-between;
    align-items: center;
  }
  
  .doc-header-logo {
    font-size: 14pt;
    font-weight: 700;
  }
  
  .doc-header-logo span {
    color: #D4A843;
  }
  
  .doc-header-info {
    font-size: 9pt;
    color: #6B7280;
    text-align: right;
  }
  
  /* Typography */
  h1 {
    font-size: 24pt;
    font-weight: 800;
    color: #001F3F;
    margin: 32px 0 16px;
    padding-bottom: 8px;
    border-bottom: 3px solid #D4A843;
  }
  
  h2 {
    font-size: 18pt;
    font-weight: 700;
    color: #001F3F;
    margin: 28px 0 12px;
    padding-left: 12px;
    border-left: 4px solid #D4A843;
  }
  
  h3 {
    font-size: 14pt;
    font-weight: 600;
    color: #003366;
    margin: 20px 0 10px;
  }
  
  h4 {
    font-size: 12pt;
    font-weight: 600;
    color: #001F3F;
    margin: 16px 0 8px;
  }
  
  p {
    margin: 10px 0;
    text-align: justify;
  }
  
  /* Tables */
  table {
    width: 100%;
    border-collapse: collapse;
    margin: 16px 0;
    font-size: 10pt;
  }
  
  th {
    background: #001F3F;
    color: white;
    padding: 10px 12px;
    text-align: left;
    font-weight: 600;
  }
  
  td {
    padding: 10px 12px;
    border-bottom: 1px solid #E5E7EB;
  }
  
  tr:nth-child(even) td {
    background: #F9FAFB;
  }
  
  /* Lists */
  ul, ol {
    margin: 12px 0;
    padding-left: 24px;
  }
  
  li {
    margin: 6px 0;
  }
  
  /* Code blocks */
  pre {
    background: #F3F4F6;
    border: 1px solid #E5E7EB;
    border-radius: 8px;
    padding: 16px;
    font-family: 'SF Mono', Monaco, monospace;
    font-size: 9pt;
    overflow-x: auto;
    margin: 16px 0;
  }
  
  code {
    background: #F3F4F6;
    padding: 2px 6px;
    border-radius: 4px;
    font-family: 'SF Mono', Monaco, monospace;
    font-size: 9pt;
  }
  
  /* Callout boxes */
  .callout {
    padding: 16px;
    border-radius: 8px;
    margin: 16px 0;
  }
  
  .callout-info {
    background: #EFF6FF;
    border-left: 4px solid #3B82F6;
  }
  
  .callout-warning {
    background: #FFFBEB;
    border-left: 4px solid #F59E0B;
  }
  
  .callout-success {
    background: #ECFDF5;
    border-left: 4px solid #10B981;
  }
  
  /* Page numbers */
  @page {
    margin: 60px 50px;
    @bottom-center {
      content: "Page " counter(page) " of " counter(pages);
      font-size: 9pt;
      color: #6B7280;
    }
    @bottom-right {
      content: "© German Select - Confidential";
      font-size: 8pt;
      color: #9CA3AF;
    }
  }
  
  /* Page breaks */
  .page-break {
    page-break-after: always;
  }
  
  /* Footer */
  .doc-footer {
    margin-top: 40px;
    padding-top: 20px;
    border-top: 2px solid #D4A843;
    font-size: 9pt;
    color: #6B7280;
    text-align: center;
  }
  
  .doc-footer strong {
    color: #001F3F;
  }
  
  /* Print optimizations */
  @media print {
    body {
      -webkit-print-color-adjust: exact !important;
      print-color-adjust: exact !important;
    }
    
    .no-print {
      display: none !important;
    }
    
    a {
      color: #001F3F;
      text-decoration: none;
    }
  }
</style>
`;

// Generate professional PDF HTML
function generatePDFDocument(title: string, subtitle: string, content: string): string {
  return `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>${title} - SelectCareOS™</title>
    ${PDF_STYLES}
</head>
<body>
    <!-- Cover Page -->
    <div class="cover-page">
        <div class="cover-badge">Official Documentation</div>
        <div class="cover-logo">SelectCare<span>OS</span>™</div>
        <div class="cover-title">${title}</div>
        <div class="cover-subtitle">${subtitle}</div>
        
        <div class="cover-meta">
            <div class="divider" style="margin: 0 auto;"></div>
            <p><strong>Generated by:</strong> ${DOCUMENT_INFO.author}</p>
            <p><strong>Powered by:</strong> ${DOCUMENT_INFO.company}</p>
            <p><strong>Website:</strong> ${DOCUMENT_INFO.website}</p>
            <div class="divider" style="margin: 20px auto;"></div>
            <p><strong>Document Version:</strong> ${DOCUMENT_INFO.version}</p>
            <p><strong>Date:</strong> ${DOCUMENT_INFO.date}</p>
            <p style="margin-top: 30px; font-size: 8pt;">${DOCUMENT_INFO.copyright}</p>
            <p style="font-size: 8pt; opacity: 0.7;">CONFIDENTIAL - For Authorized Personnel Only</p>
        </div>
    </div>
    
    <!-- Document Header (repeats on each page) -->
    <div class="doc-header">
        <div class="doc-header-logo">SelectCare<span>OS</span>™</div>
        <div class="doc-header-info">
            ${title}<br>
            Version ${DOCUMENT_INFO.version} | ${DOCUMENT_INFO.date}
        </div>
    </div>
    
    <!-- Main Content -->
    <main>
        ${content}
    </main>
    
    <!-- Document Footer -->
    <div class="doc-footer">
        <p><strong>${DOCUMENT_INFO.company}</strong></p>
        <p>${DOCUMENT_INFO.website} | ${DOCUMENT_INFO.email}</p>
        <p style="margin-top: 12px;">${DOCUMENT_INFO.copyright}</p>
        <p style="font-size: 8pt; color: #9CA3AF;">This document is confidential and intended for authorized personnel only. 
        Unauthorized distribution is prohibited.</p>
    </div>
    
    <script>
        // Auto-print for PDF generation
        // window.onload = () => window.print();
    </script>
</body>
</html>`;
}

// Convert markdown to HTML (basic conversion)
function markdownToHTML(markdown: string): string {
  let html = markdown
    // Headers
    .replace(/^### (.*$)/gm, '<h3>$1</h3>')
    .replace(/^## (.*$)/gm, '<h2>$1</h2>')
    .replace(/^# (.*$)/gm, '<h1>$1</h1>')
    // Bold
    .replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>')
    // Italic
    .replace(/\*(.*?)\*/g, '<em>$1</em>')
    // Code blocks
    .replace(/```(\w+)?\n([\s\S]*?)```/g, '<pre><code>$2</code></pre>')
    // Inline code
    .replace(/`([^`]+)`/g, '<code>$1</code>')
    // Links
    .replace(/\[([^\]]+)\]\(([^)]+)\)/g, '<a href="$2">$1</a>')
    // Horizontal rules
    .replace(/^---$/gm, '<hr>')
    // Tables (basic)
    .replace(/\|(.+)\|/g, (match) => {
      const cells = match.split('|').filter(c => c.trim());
      const isHeader = cells.some(c => c.includes('---'));
      if (isHeader) return '';
      return '<tr>' + cells.map(c => `<td>${c.trim()}</td>`).join('') + '</tr>';
    })
    // Unordered lists
    .replace(/^\s*[-*]\s+(.*)$/gm, '<li>$1</li>')
    // Ordered lists
    .replace(/^\s*\d+\.\s+(.*)$/gm, '<li>$1</li>')
    // Paragraphs
    .replace(/\n\n/g, '</p><p>')
    // Line breaks
    .replace(/\n/g, '<br>');
  
  // Wrap lists
  html = html.replace(/(<li>.*?<\/li>)+/gs, '<ul>$&</ul>');
  
  return `<p>${html}</p>`;
}

// Route: Get document content as HTML
docsRouter.get('/:docType/content', async (c) => {
  const docType = c.req.param('docType');
  
  // Map document types to files
  const docFiles: Record<string, string> = {
    'mvp-specification': 'MVP_SPECIFICATION_v1.0.md',
    'functional-specification': 'MVP_SPECIFICATION_v1.0.md', // Extract FSD section
    'technical-specification': 'MVP_SPECIFICATION_v1.0.md', // Extract TSD section
    'development-roadmap': 'MVP_SPECIFICATION_v1.0.md' // Extract Roadmap section
  };
  
  const fileName = docFiles[docType];
  if (!fileName) {
    return c.text('Document not found', 404);
  }
  
  try {
    // Read markdown file (in production, this would be from KV or file system)
    // For now, return a summary
    const content = `
      <h1>Document Loading</h1>
      <p>The full document content would be loaded from the server.</p>
      <p>For now, please use the PDF download option to get the complete document.</p>
      <p><a href="/api/docs/${docType}/pdf" class="btn">Download PDF</a></p>
    `;
    
    return c.html(content);
  } catch (error) {
    return c.text('Error loading document', 500);
  }
});

// Route: Generate PDF (HTML for print/save as PDF)
docsRouter.get('/:docType/pdf', async (c) => {
  const docType = c.req.param('docType');
  
  // Document metadata
  const documents: Record<string, { title: string; subtitle: string; content: string }> = {
    'mvp-specification': {
      title: 'MVP Specification Document',
      subtitle: 'Complete Technical & Functional Specification for German Select Medical Tourism Platform',
      content: getMVPSpecContent()
    },
    'functional-specification': {
      title: 'Functional Specification Document (FSD)',
      subtitle: 'User Stories, Requirements & Feature Specifications',
      content: getFSDContent()
    },
    'technical-specification': {
      title: 'Technical Specification Document (TSD)',
      subtitle: 'Architecture, Database Design & API Specifications',
      content: getTSDContent()
    },
    'development-roadmap': {
      title: 'MVP Development Roadmap',
      subtitle: 'Phase-by-Phase Implementation Plan & Milestones',
      content: getRoadmapContent()
    }
  };
  
  const doc = documents[docType];
  if (!doc) {
    return c.text('Document not found', 404);
  }
  
  const html = generatePDFDocument(doc.title, doc.subtitle, doc.content);
  
  // Set headers for PDF-like display
  c.header('Content-Type', 'text/html; charset=utf-8');
  c.header('Content-Disposition', `inline; filename="${docType}.html"`);
  
  return c.html(html);
});

// Content generators
function getMVPSpecContent(): string {
  return `
    <h1>1. Executive Summary</h1>
    
    <h2>1.1 Vision Statement</h2>
    <p>SelectCareOS™ is a groundbreaking digital health platform revolutionizing cross-border healthcare between Egypt and Germany. We combine German medical excellence with Red Sea therapeutic recovery, delivered through world-class telemedicine, intelligent booking systems, and AI-powered healthcare solutions.</p>
    
    <h2>1.2 Problem Statement</h2>
    <table>
      <tr><th>Problem</th><th>Impact</th><th>Our Solution</th></tr>
      <tr><td>German healthcare waitlists</td><td>6+ months for elective procedures</td><td>2-6 weeks with SelectCareOS</td></tr>
      <tr><td>High European medical costs</td><td>€22,000+ for gastric sleeve</td><td>€7,500 with German surgeons</td></tr>
      <tr><td>Fragmented medical tourism</td><td>Poor coordination, communication gaps</td><td>Integrated end-to-end platform</td></tr>
      <tr><td>Post-op recovery challenges</td><td>Limited monitoring, poor outcomes</td><td>Red Sea recovery + 12mo digital follow-up</td></tr>
      <tr><td>Language barriers</td><td>Miscommunication, safety risks</td><td>Native German/English/Arabic support</td></tr>
    </table>
    
    <h2>1.3 Target Market</h2>
    <h3>Primary Markets</h3>
    <ul>
      <li><strong>German Patients:</strong> 83M population, high healthcare costs, long waitlists</li>
      <li><strong>Medical Tourists:</strong> 14-20M annually worldwide, growing 15-25% YoY</li>
      <li><strong>Expats in MENA:</strong> 500K+ Germans in UAE, Egypt, Qatar</li>
    </ul>
    
    <h2>1.4 Competitive Advantage</h2>
    <table>
      <tr><th>Differentiator</th><th>SelectCareOS</th><th>Turkish Clinics</th><th>Thai Medical Tourism</th></tr>
      <tr><td>Surgeon Quality</td><td>German Board-Certified</td><td>Turkish Licensed</td><td>Thai Licensed</td></tr>
      <tr><td>Price vs Germany</td><td>50-65% savings</td><td>70-80% savings</td><td>60-70% savings</td></tr>
      <tr><td>Digital Platform</td><td>Full integration</td><td>Minimal</td><td>Basic</td></tr>
      <tr><td>Post-Op Monitoring</td><td>12mo IoT/AI</td><td>None</td><td>Limited</td></tr>
      <tr><td>Recovery Experience</td><td>5-star Red Sea resorts</td><td>Hotel rooms</td><td>Hospital/Hotel</td></tr>
    </table>
    
    <h2>1.5 Revenue Model</h2>
    <table>
      <tr><th>Revenue Stream</th><th>Description</th><th>Target (Year 1)</th></tr>
      <tr><td>Consultation Commission</td><td>20% platform fee</td><td>€150K</td></tr>
      <tr><td>Package Booking Fees</td><td>15% on surgeries/retreats</td><td>€400K</td></tr>
      <tr><td>Premium Subscriptions</td><td>€29-199/mo patient plans</td><td>€100K</td></tr>
      <tr><td>Affiliate Program</td><td>5-15% partner commissions</td><td>€50K</td></tr>
      <tr><td>Marketplace</td><td>12-22% product margins</td><td>€75K</td></tr>
      <tr><td><strong>Total Year 1 Target</strong></td><td></td><td><strong>€775K</strong></td></tr>
    </table>
    
    <div class="page-break"></div>
    
    <h1>2. Platform Analysis - Current State</h1>
    
    <h2>2.1 Existing Implementation (v2.5.0)</h2>
    <p>SelectCareOS already has significant functionality implemented:</p>
    
    <h3>✅ Completed Features</h3>
    
    <h4>Core Platform</h4>
    <ul>
      <li><strong>Technology Stack:</strong> Hono (TypeScript) + Cloudflare Pages/Workers + D1 Database</li>
      <li><strong>91 TypeScript Files</strong> across services, routes, pages, components</li>
      <li><strong>31 Automated Tests</strong> passing with comprehensive coverage</li>
    </ul>
    
    <h4>Telemedicine System (Instant Connect v2.3.0)</h4>
    <ul>
      <li>Real-time video consultations via Jitsi Meet (FREE, no API key)</li>
      <li>Smart doctor-patient matching with AI scoring</li>
      <li>Priority queue management (Emergency > Urgent > Routine)</li>
      <li>Doctor dashboard with schedule, earnings, availability</li>
      <li>Multi-language support (EN/DE/AR/FR)</li>
    </ul>
    
    <h4>Booking System</h4>
    <ul>
      <li>Three consultation types: Online, Onsite, Hybrid</li>
      <li>Stripe payment integration (ready for production)</li>
      <li>Commission calculation (20% consultation, 15% packages)</li>
      <li>Affiliate tracking and commission system</li>
    </ul>
    
    <h4>Medical Retreats & Accommodations</h4>
    <ul>
      <li>4 Medical Retreat programs (Longevity, Weight Loss, Recovery, Detox)</li>
      <li>5 SELECT Hotels (5-star properties in Hurghada)</li>
      <li>Package builder with add-ons</li>
    </ul>
    
    <h4>AI Health Features (MediSense AI Pro v3.0)</h4>
    <ul>
      <li>227+ symptoms across 14 body systems (ICD-11 aligned)</li>
      <li>37 conditions with SNOMED-CT coding</li>
      <li>21 medications with drug interaction checking</li>
      <li>4-level urgency triage</li>
      <li>Fuzzy symptom matching</li>
    </ul>
    
    <div class="page-break"></div>
    
    <h1>3. Core MVP Features</h1>
    
    <h2>3.1 Telemedicine Platform</h2>
    <p>HIPAA-compliant WebRTC video rooms with in-session tools including screen sharing, virtual backgrounds, consent-based recording, and real-time chat. Features integrated clinical notes with auto-save, secure file uploads with end-to-end encryption, and comprehensive session management.</p>
    
    <h2>3.2 Intelligent Multi-Modal Booking</h2>
    <p>Three consultation types (Online, Onsite in Egypt, Hybrid Co-Expert), smart scheduling with Google Calendar/Outlook/iCal integration, automatic time-zone handling for Egypt-Germany, conflict prevention, symptom-based provider matching, insurance verification, and price transparency.</p>
    
    <h2>3.3 Therapeutic Retreat Booking</h2>
    <p>Catalog of medically-supervised post-op retreats at 5-star Red Sea resorts with accommodation options, package builder (Single Treatment, All-Inclusive, Add-Ons), medical integration with primary care access, 24/7 nursing, and emergency protocols.</p>
    
    <h2>3.4 User Management</h2>
    <p>Four account types (Provider: Doctor, CRM Staff, Admin; Patient) with comprehensive profiles, dashboards, and role-based access controls. Patient health history vault with secure data storage.</p>
    
    <h2>3.5 E-Commerce & Payments</h2>
    <p>Shopping cart for consultations, retreats, treatments, and packages. Multi-currency support (EGP, EUR) with real-time conversion. Payment gateways include Stripe, PayPal, and local methods (Fawry, Vodafone Cash). Itemized invoices, insurance co-pays, and refund processing.</p>
    
    <div class="page-break"></div>
    
    <h1>4. Success Metrics</h1>
    
    <h2>4.1 Key Performance Indicators</h2>
    <table>
      <tr><th>Metric</th><th>Target (MVP)</th><th>Timeline</th></tr>
      <tr><td>Registered Patients</td><td>500+</td><td>3 months</td></tr>
      <tr><td>Verified Doctors</td><td>50+</td><td>3 months</td></tr>
      <tr><td>Completed Consultations</td><td>100+</td><td>3 months</td></tr>
      <tr><td>Booking Completion Rate</td><td>70%</td><td>Ongoing</td></tr>
      <tr><td>Average Video Session</td><td>25+ minutes</td><td>Ongoing</td></tr>
      <tr><td>User Rating</td><td>4.5+ stars</td><td>Ongoing</td></tr>
      <tr><td>GMV</td><td>$50K+</td><td>6 months</td></tr>
      <tr><td>Take-rate</td><td>20%</td><td>Ongoing</td></tr>
      <tr><td>Retreat Bookings</td><td>5+</td><td>6 months</td></tr>
      <tr><td>Platform Uptime</td><td>99.5%</td><td>Ongoing</td></tr>
      <tr><td>Page Load Time</td><td><2 seconds</td><td>Ongoing</td></tr>
      <tr><td>HIPAA Violations</td><td>Zero</td><td>Ongoing</td></tr>
    </table>
  `;
}

function getFSDContent(): string {
  return `
    <h1>Functional Specification Document (FSD)</h1>
    
    <h2>1. User Personas</h2>
    
    <h3>1.1 Patient Personas</h3>
    
    <h4>Persona 1: Klaus (German Patient)</h4>
    <table>
      <tr><td><strong>Name</strong></td><td>Klaus Müller</td></tr>
      <tr><td><strong>Age</strong></td><td>52</td></tr>
      <tr><td><strong>Location</strong></td><td>Munich, Germany</td></tr>
      <tr><td><strong>Occupation</strong></td><td>IT Manager</td></tr>
      <tr><td><strong>Medical Need</strong></td><td>Gastric Sleeve Surgery</td></tr>
      <tr><td><strong>Budget</strong></td><td>€10,000-15,000 total</td></tr>
      <tr><td><strong>Tech Comfort</strong></td><td>Medium (smartphone, email, Zoom)</td></tr>
      <tr><td><strong>Languages</strong></td><td>German (native), English (basic)</td></tr>
    </table>
    
    <p><strong>Goals:</strong></p>
    <ul>
      <li>Find German-quality surgery at affordable price</li>
      <li>Minimal time away from work (2-3 weeks)</li>
      <li>Comprehensive post-op support</li>
    </ul>
    
    <p><strong>Pain Points:</strong></p>
    <ul>
      <li>Doesn't trust "cheap" Turkish clinics</li>
      <li>Worried about language barriers</li>
      <li>Needs ongoing care coordination</li>
    </ul>
    
    <h4>Persona 2: Ahmed (Egyptian Expat)</h4>
    <table>
      <tr><td><strong>Name</strong></td><td>Ahmed Hassan</td></tr>
      <tr><td><strong>Age</strong></td><td>38</td></tr>
      <tr><td><strong>Location</strong></td><td>Dubai, UAE (Egyptian citizen)</td></tr>
      <tr><td><strong>Occupation</strong></td><td>Engineer</td></tr>
      <tr><td><strong>Medical Need</strong></td><td>Post-bariatric body contouring</td></tr>
      <tr><td><strong>Tech Comfort</strong></td><td>High (uses multiple apps daily)</td></tr>
      <tr><td><strong>Languages</strong></td><td>Arabic (native), English (fluent)</td></tr>
    </table>
    
    <div class="page-break"></div>
    
    <h2>2. Telemedicine Features</h2>
    
    <h3>2.1 Video Consultation Room</h3>
    <ul>
      <li>HIPAA-compliant WebRTC video with HD quality</li>
      <li>Screen sharing for medical imaging review</li>
      <li>Virtual backgrounds for privacy</li>
      <li>Consent-based session recording</li>
      <li>Real-time chat sidebar</li>
      <li>Connection quality monitoring</li>
    </ul>
    
    <h3>2.2 Pre-Call Device Testing</h3>
    <ul>
      <li>Camera preview and selection</li>
      <li>Microphone test with audio visualization</li>
      <li>Speaker test with sample audio</li>
      <li>Network quality assessment</li>
    </ul>
    
    <h3>2.3 Virtual Waiting Room</h3>
    <ul>
      <li>Queue position display</li>
      <li>Estimated wait time</li>
      <li>Doctor availability status</li>
      <li>Pre-consultation forms</li>
    </ul>
    
    <h2>3. Booking System Requirements</h2>
    
    <h3>3.1 Consultation Types</h3>
    <table>
      <tr><th>Type</th><th>Description</th><th>Price Range</th></tr>
      <tr><td>Online</td><td>Video consultation from anywhere</td><td>€50-150</td></tr>
      <tr><td>Onsite (Egypt)</td><td>In-person at Hurghada clinic</td><td>€100-200</td></tr>
      <tr><td>Hybrid Co-Expert</td><td>Egyptian onsite + German online specialist</td><td>€150-300</td></tr>
    </table>
    
    <h3>3.2 Scheduling Features</h3>
    <ul>
      <li>Calendar integration (Google, Outlook, iCal)</li>
      <li>Automatic time-zone conversion (Egypt/Germany)</li>
      <li>Buffer time between appointments</li>
      <li>Conflict detection and prevention</li>
      <li>Automated reminders (email, SMS, push)</li>
    </ul>
    
    <div class="page-break"></div>
    
    <h2>4. Therapeutic Retreat Booking</h2>
    
    <h3>4.1 Retreat Programs</h3>
    <table>
      <tr><th>Program</th><th>Duration</th><th>Price Range</th></tr>
      <tr><td>Longevity Reset Retreat</td><td>7 nights</td><td>€8,500-12,000</td></tr>
      <tr><td>Weight Loss Transformation</td><td>14 nights</td><td>€6,500-9,500</td></tr>
      <tr><td>Post-Surgery Recovery</td><td>10 nights</td><td>€4,500-7,500</td></tr>
      <tr><td>Detox & Wellness</td><td>5 nights</td><td>€3,500-5,500</td></tr>
    </table>
    
    <h3>4.2 Package Builder</h3>
    <ul>
      <li>Base package selection</li>
      <li>Accommodation upgrade options</li>
      <li>Treatment add-ons</li>
      <li>Family accommodation</li>
      <li>Airport transfer options</li>
      <li>Excursion packages</li>
    </ul>
    
    <h2>5. User Management</h2>
    
    <h3>5.1 Account Types</h3>
    <table>
      <tr><th>Role</th><th>Permissions</th></tr>
      <tr><td>Patient</td><td>Book consultations, view records, manage profile</td></tr>
      <tr><td>Doctor</td><td>Manage schedule, conduct consultations, write prescriptions</td></tr>
      <tr><td>CRM Staff</td><td>Manage bookings, patient support, reporting</td></tr>
      <tr><td>Admin</td><td>Full system access, user management, analytics</td></tr>
    </table>
    
    <h3>5.2 Patient Health Vault</h3>
    <ul>
      <li>Secure document storage</li>
      <li>Medical history tracking</li>
      <li>Medication records</li>
      <li>Lab results integration</li>
      <li>FHIR-compatible data export</li>
    </ul>
  `;
}

function getTSDContent(): string {
  return `
    <h1>Technical Specification Document (TSD)</h1>
    
    <h2>1. System Architecture</h2>
    
    <h3>1.1 Technology Stack</h3>
    <table>
      <tr><th>Layer</th><th>Technology</th><th>Purpose</th></tr>
      <tr><td>Frontend</td><td>TypeScript + Tailwind CSS</td><td>Responsive UI</td></tr>
      <tr><td>Backend</td><td>Hono Framework</td><td>API & Server Logic</td></tr>
      <tr><td>Runtime</td><td>Cloudflare Workers</td><td>Edge Computing</td></tr>
      <tr><td>Database</td><td>Cloudflare D1 (SQLite)</td><td>Primary Data Store</td></tr>
      <tr><td>Cache</td><td>Cloudflare KV</td><td>Session & Cache</td></tr>
      <tr><td>Storage</td><td>Cloudflare R2</td><td>File Storage</td></tr>
      <tr><td>Video</td><td>Jitsi Meet / Daily.co</td><td>Telemedicine</td></tr>
      <tr><td>Payments</td><td>Stripe</td><td>Payment Processing</td></tr>
    </table>
    
    <h3>1.2 Architecture Diagram</h3>
    <pre>
┌─────────────────────────────────────────────────────────────┐
│                    SELECTCAREOS™ ARCHITECTURE                │
├─────────────────────────────────────────────────────────────┤
│                                                              │
│  ┌──────────┐    ┌──────────┐    ┌──────────┐              │
│  │  Mobile  │    │   Web    │    │  Doctor  │              │
│  │   App    │    │  Portal  │    │Dashboard │              │
│  └────┬─────┘    └────┬─────┘    └────┬─────┘              │
│       │               │               │                     │
│       └───────────────┼───────────────┘                     │
│                       ▼                                      │
│            ┌──────────────────┐                             │
│            │  Cloudflare CDN  │                             │
│            │   (Edge Layer)   │                             │
│            └────────┬─────────┘                             │
│                     ▼                                        │
│            ┌──────────────────┐                             │
│            │ Cloudflare Workers│                             │
│            │   (Hono API)     │                             │
│            └────────┬─────────┘                             │
│                     │                                        │
│     ┌───────────────┼───────────────┐                       │
│     ▼               ▼               ▼                       │
│  ┌──────┐      ┌──────┐      ┌──────┐                      │
│  │  D1  │      │  KV  │      │  R2  │                      │
│  │(SQL) │      │(Cache)│     │(Files)│                      │
│  └──────┘      └──────┘      └──────┘                      │
│                                                              │
│  External Services:                                          │
│  ┌──────┐ ┌──────┐ ┌──────┐ ┌──────┐                       │
│  │Stripe│ │Jitsi │ │Twilio│ │OpenAI│                       │
│  └──────┘ └──────┘ └──────┘ └──────┘                       │
│                                                              │
└─────────────────────────────────────────────────────────────┘
    </pre>
    
    <div class="page-break"></div>
    
    <h2>2. Database Design</h2>
    
    <h3>2.1 Core Tables</h3>
    <pre>
-- Users Table
CREATE TABLE users (
    id TEXT PRIMARY KEY,
    email TEXT UNIQUE NOT NULL,
    password_hash TEXT NOT NULL,
    role TEXT CHECK(role IN ('patient','doctor','admin','affiliate')),
    status TEXT DEFAULT 'active',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- Doctors Table
CREATE TABLE doctors (
    id TEXT PRIMARY KEY,
    user_id TEXT REFERENCES users(id),
    name TEXT NOT NULL,
    specialization TEXT NOT NULL,
    qualifications TEXT,
    languages TEXT,
    consultation_fee DECIMAL(10,2),
    rating DECIMAL(3,2),
    is_premium BOOLEAN DEFAULT FALSE,
    FOREIGN KEY (user_id) REFERENCES users(id)
);

-- Consultations Table
CREATE TABLE consultations (
    id TEXT PRIMARY KEY,
    patient_id TEXT REFERENCES users(id),
    doctor_id TEXT REFERENCES doctors(id),
    type TEXT CHECK(type IN ('online','onsite','hybrid')),
    status TEXT DEFAULT 'scheduled',
    scheduled_at DATETIME NOT NULL,
    started_at DATETIME,
    ended_at DATETIME,
    video_room_id TEXT,
    price DECIMAL(10,2),
    platform_fee DECIMAL(10,2),
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
    </pre>
    
    <h2>3. API Specifications</h2>
    
    <h3>3.1 Authentication Endpoints</h3>
    <table>
      <tr><th>Method</th><th>Endpoint</th><th>Description</th></tr>
      <tr><td>POST</td><td>/api/auth/register</td><td>User registration</td></tr>
      <tr><td>POST</td><td>/api/auth/login</td><td>User authentication</td></tr>
      <tr><td>POST</td><td>/api/auth/refresh</td><td>Refresh JWT token</td></tr>
      <tr><td>POST</td><td>/api/auth/logout</td><td>Invalidate session</td></tr>
    </table>
    
    <h3>3.2 Booking Endpoints</h3>
    <table>
      <tr><th>Method</th><th>Endpoint</th><th>Description</th></tr>
      <tr><td>GET</td><td>/api/doctors</td><td>List available doctors</td></tr>
      <tr><td>GET</td><td>/api/doctors/:id/slots</td><td>Get available slots</td></tr>
      <tr><td>POST</td><td>/api/bookings</td><td>Create booking</td></tr>
      <tr><td>GET</td><td>/api/bookings/:id</td><td>Get booking details</td></tr>
      <tr><td>PATCH</td><td>/api/bookings/:id</td><td>Update booking</td></tr>
      <tr><td>DELETE</td><td>/api/bookings/:id</td><td>Cancel booking</td></tr>
    </table>
    
    <div class="page-break"></div>
    
    <h2>4. Security & Compliance</h2>
    
    <h3>4.1 Authentication & Authorization</h3>
    <ul>
      <li>OAuth 2.0 with JWT tokens</li>
      <li>Role-Based Access Control (RBAC)</li>
      <li>Multi-Factor Authentication (MFA)</li>
      <li>Session management with secure cookies</li>
    </ul>
    
    <h3>4.2 Data Protection</h3>
    <ul>
      <li>TLS 1.3 encryption in transit</li>
      <li>AES-256 encryption at rest</li>
      <li>End-to-end encryption for medical files</li>
      <li>GDPR-compliant data handling</li>
      <li>HIPAA-compliant PHI storage</li>
    </ul>
    
    <h3>4.3 Compliance Standards</h3>
    <table>
      <tr><th>Standard</th><th>Status</th><th>Notes</th></tr>
      <tr><td>HIPAA</td><td>Compliant</td><td>PHI handling, audit logs</td></tr>
      <tr><td>GDPR</td><td>Compliant</td><td>EU data protection</td></tr>
      <tr><td>ISO 27001</td><td>In Progress</td><td>Information security</td></tr>
      <tr><td>SOC 2</td><td>Planned</td><td>Service organization controls</td></tr>
    </table>
  `;
}

function getRoadmapContent(): string {
  return `
    <h1>MVP Development Roadmap</h1>
    
    <h2>Phase 1: Foundation (Months 1-4)</h2>
    
    <h3>Sprint 1-2: User Authentication & Onboarding</h3>
    <table>
      <tr><th>Task</th><th>Duration</th><th>Dependencies</th></tr>
      <tr><td>JWT authentication implementation</td><td>3 days</td><td>None</td></tr>
      <tr><td>User registration flow</td><td>2 days</td><td>Auth</td></tr>
      <tr><td>Email verification</td><td>2 days</td><td>Registration</td></tr>
      <tr><td>Password reset flow</td><td>1 day</td><td>Auth</td></tr>
      <tr><td>Patient onboarding wizard</td><td>3 days</td><td>Registration</td></tr>
      <tr><td>Doctor verification process</td><td>2 days</td><td>Registration</td></tr>
    </table>
    
    <h3>Sprint 3-4: Doctor Profile & Availability Management</h3>
    <table>
      <tr><th>Task</th><th>Duration</th><th>Dependencies</th></tr>
      <tr><td>Doctor profile CRUD</td><td>3 days</td><td>Auth</td></tr>
      <tr><td>Availability calendar</td><td>4 days</td><td>Profile</td></tr>
      <tr><td>Time slot management</td><td>3 days</td><td>Calendar</td></tr>
      <tr><td>Specialization & services setup</td><td>2 days</td><td>Profile</td></tr>
    </table>
    
    <h3>Sprint 5-7: Basic Online Booking</h3>
    <table>
      <tr><th>Task</th><th>Duration</th><th>Dependencies</th></tr>
      <tr><td>Doctor search & filtering</td><td>3 days</td><td>Profiles</td></tr>
      <tr><td>Availability display</td><td>2 days</td><td>Calendar</td></tr>
      <tr><td>Booking creation flow</td><td>4 days</td><td>Search</td></tr>
      <tr><td>Booking confirmation & reminders</td><td>3 days</td><td>Booking</td></tr>
      <tr><td>Booking management (reschedule/cancel)</td><td>3 days</td><td>Booking</td></tr>
    </table>
    
    <div class="page-break"></div>
    
    <h3>Sprint 8-10: Video Consultation Room</h3>
    <table>
      <tr><th>Task</th><th>Duration</th><th>Dependencies</th></tr>
      <tr><td>Jitsi Meet integration</td><td>5 days</td><td>Booking</td></tr>
      <tr><td>Pre-call device testing</td><td>3 days</td><td>Video</td></tr>
      <tr><td>Virtual waiting room</td><td>3 days</td><td>Video</td></tr>
      <tr><td>In-call controls (mute, camera, etc.)</td><td>2 days</td><td>Video</td></tr>
      <tr><td>Screen sharing</td><td>2 days</td><td>Video</td></tr>
      <tr><td>Session recording (consent-based)</td><td>3 days</td><td>Video</td></tr>
    </table>
    
    <h3>Sprint 11-12: Payment Integration</h3>
    <table>
      <tr><th>Task</th><th>Duration</th><th>Dependencies</th></tr>
      <tr><td>Stripe integration</td><td>3 days</td><td>Booking</td></tr>
      <tr><td>Multi-currency support</td><td>2 days</td><td>Stripe</td></tr>
      <tr><td>Payment flow (pre-pay for consultations)</td><td>3 days</td><td>Stripe</td></tr>
      <tr><td>Invoice generation</td><td>2 days</td><td>Payment</td></tr>
      <tr><td>Refund processing</td><td>2 days</td><td>Payment</td></tr>
    </table>
    
    <h2>Phase 2: Enhancement (Months 5-8)</h2>
    
    <h3>Key Deliverables</h3>
    <ul>
      <li>Retreat Catalog & Booking</li>
      <li>AI Symptom Analyzer (MediSense)</li>
      <li>AI Concierge & Health Insights</li>
      <li>Remote Health Monitoring Groundwork</li>
      <li>CRM & Admin Tools</li>
    </ul>
    
    <h2>Phase 3: Scale (Months 9-12)</h2>
    
    <h3>Key Deliverables</h3>
    <ul>
      <li>Subscription Management</li>
      <li>Remote Health Monitoring (Wearables)</li>
      <li>AI Diagnostics & Imaging Analysis</li>
      <li>Open-Source EHR Integration (HL7 FHIR)</li>
      <li>Marketplace Expansion</li>
      <li>Mobile App Development</li>
    </ul>
    
    <div class="page-break"></div>
    
    <h2>Success Metrics & KPIs</h2>
    
    <table>
      <tr><th>Metric</th><th>Month 4</th><th>Month 8</th><th>Month 12</th></tr>
      <tr><td>Registered Patients</td><td>500</td><td>2,000</td><td>5,000</td></tr>
      <tr><td>Active Doctors</td><td>50</td><td>100</td><td>200</td></tr>
      <tr><td>Monthly Consultations</td><td>100</td><td>500</td><td>1,500</td></tr>
      <tr><td>Booking Completion Rate</td><td>70%</td><td>80%</td><td>85%</td></tr>
      <tr><td>Monthly Revenue</td><td>€50K</td><td>€150K</td><td>€400K</td></tr>
      <tr><td>Platform Uptime</td><td>99.5%</td><td>99.9%</td><td>99.99%</td></tr>
    </table>
    
    <h2>Risk Assessment</h2>
    
    <table>
      <tr><th>Risk</th><th>Probability</th><th>Impact</th><th>Mitigation</th></tr>
      <tr><td>Regulatory Compliance</td><td>Medium</td><td>High</td><td>Regular audits, legal counsel</td></tr>
      <tr><td>Video Quality Issues</td><td>Medium</td><td>Medium</td><td>Adaptive bitrate, audio fallback</td></tr>
      <tr><td>Doctor Adoption</td><td>Medium</td><td>High</td><td>Incentives, easy onboarding</td></tr>
      <tr><td>Payment Fraud</td><td>Low</td><td>High</td><td>Stripe Radar, 3D Secure</td></tr>
      <tr><td>Scope Creep</td><td>High</td><td>Medium</td><td>Strict MVP scope, sprint reviews</td></tr>
    </table>
  `;
}

export default docsRouter;
