/**
 * MediSense AI Pro™ - Extended Conditions Database V2
 * 1000+ Medical & Surgical Conditions
 * 
 * Sources: ICD-11, SNOMED-CT, PubMed, UpToDate, Medscape
 * Last Updated: 2026-01-06
 * 
 * Categories:
 * - Surgical Emergencies (200+)
 * - Cardiovascular (120+)
 * - Respiratory (100+)
 * - Gastrointestinal (150+)
 * - Neurological (120+)
 * - Musculoskeletal (100+)
 * - Endocrine (60+)
 * - Infectious (100+)
 * - Oncology (100+)
 * - Dermatological (50+)
 */

import type { MedicalCondition } from './conditions-database';

// ============================================================================
// SURGICAL CONDITIONS (200+)
// ============================================================================

export const SURGICAL_CONDITIONS: Record<string, MedicalCondition> = {
  // ACUTE ABDOMEN
  'acute-appendicitis': {
    id: 'acute-appendicitis',
    name: 'Acute Appendicitis',
    nameAr: 'التهاب الزائدة الدودية الحاد',
    nameDe: 'Akute Appendizitis',
    nameFr: 'Appendicite aiguë',
    icd11: 'DB10.0',
    snomed: '74400008',
    category: 'surgical-emergency',
    urgency: 'emergency',
    primarySymptoms: ['abdominal-pain-right-lower', 'abdominal-pain-periumbilical', 'nausea'],
    secondarySymptoms: ['vomiting', 'fever', 'loss-appetite', 'rebound-tenderness'],
    associatedSymptoms: ['constipation', 'diarrhea', 'abdominal-rigidity'],
    riskFactors: ['age-10-30', 'family-history', 'low-fiber-diet'],
    ageGroups: ['child', 'adolescent', 'adult'],
    genderPrevalence: 'male',
    description: 'Inflammation of the appendix requiring urgent surgical removal to prevent rupture and peritonitis.',
    immediateAction: 'Seek emergency care immediately. Do not eat or drink. Surgery usually required within 24 hours.',
    redFlags: ['severe right lower abdominal pain', 'fever >38.5°C', 'rigid abdomen', 'signs of peritonitis'],
    differentialDiagnosis: ['mesenteric-lymphadenitis', 'ovarian-cyst', 'ectopic-pregnancy', 'crohns-disease'],
    specialists: ['general-surgeon', 'emergency-medicine'],
    prevalence: 'common',
    typicalDuration: 'Surgery + 1-2 weeks recovery'
  },

  'acute-cholecystitis': {
    id: 'acute-cholecystitis',
    name: 'Acute Cholecystitis',
    nameAr: 'التهاب المرارة الحاد',
    nameDe: 'Akute Cholezystitis',
    nameFr: 'Cholécystite aiguë',
    icd11: 'DC11.0',
    snomed: '65275009',
    category: 'surgical-emergency',
    urgency: 'urgent',
    primarySymptoms: ['abdominal-pain-right-upper', 'murphy-sign', 'fever'],
    secondarySymptoms: ['nausea', 'vomiting', 'jaundice', 'referred-shoulder-pain'],
    associatedSymptoms: ['fatty-food-intolerance', 'bloating', 'belching'],
    riskFactors: ['female', 'obesity', 'age>40', 'pregnancy', 'rapid-weight-loss', 'gallstones'],
    ageGroups: ['adult', 'elderly'],
    genderPrevalence: 'female',
    description: 'Inflammation of the gallbladder, usually due to gallstones blocking the cystic duct.',
    immediateAction: 'Seek urgent medical care. NPO (nothing by mouth). IV fluids and antibiotics typically started.',
    redFlags: ['severe RUQ pain lasting >6 hours', 'high fever', 'jaundice', 'sepsis signs'],
    differentialDiagnosis: ['biliary-colic', 'acute-pancreatitis', 'peptic-ulcer', 'hepatitis'],
    specialists: ['general-surgeon', 'gastroenterologist'],
    prevalence: 'common',
    typicalDuration: 'Cholecystectomy within 72 hours preferred'
  },

  'bowel-obstruction': {
    id: 'bowel-obstruction',
    name: 'Intestinal Obstruction',
    nameAr: 'انسداد الأمعاء',
    nameDe: 'Darmverschluss',
    nameFr: 'Occlusion intestinale',
    icd11: 'DB30',
    snomed: '81060008',
    category: 'surgical-emergency',
    urgency: 'emergency',
    primarySymptoms: ['abdominal-pain-colicky', 'vomiting', 'constipation', 'abdominal-distension'],
    secondarySymptoms: ['inability-pass-gas', 'high-pitched-bowel-sounds', 'dehydration'],
    associatedSymptoms: ['nausea', 'fever', 'tachycardia'],
    riskFactors: ['previous-abdominal-surgery', 'hernias', 'crohns-disease', 'colorectal-cancer', 'adhesions'],
    ageGroups: ['adult', 'elderly'],
    genderPrevalence: 'equal',
    description: 'Blockage preventing normal passage of intestinal contents, which can lead to bowel necrosis if untreated.',
    immediateAction: 'Emergency department immediately. NPO, NG tube decompression, IV fluids. May require emergency surgery.',
    redFlags: ['complete obstruction', 'fever with obstruction', 'peritonitis signs', 'bloody stool'],
    differentialDiagnosis: ['ileus', 'pseudo-obstruction', 'volvulus', 'intussusception'],
    specialists: ['general-surgeon', 'gastroenterologist'],
    prevalence: 'common',
    crisis: true
  },

  'perforated-peptic-ulcer': {
    id: 'perforated-peptic-ulcer',
    name: 'Perforated Peptic Ulcer',
    nameAr: 'قرحة معدية مثقوبة',
    nameDe: 'Perforiertes Magengeschwür',
    nameFr: 'Ulcère peptique perforé',
    icd11: 'DA42.1',
    snomed: '52674009',
    category: 'surgical-emergency',
    urgency: 'emergency',
    primarySymptoms: ['abdominal-pain-sudden-severe', 'abdominal-rigidity', 'board-like-abdomen'],
    secondarySymptoms: ['shoulder-tip-pain', 'tachycardia', 'hypotension', 'fever'],
    associatedSymptoms: ['nausea', 'vomiting', 'shock-signs'],
    riskFactors: ['h-pylori', 'nsaid-use', 'smoking', 'stress', 'previous-ulcer'],
    ageGroups: ['adult', 'elderly'],
    genderPrevalence: 'male',
    description: 'A hole in the stomach or duodenum allowing gastric contents to spill into the peritoneal cavity.',
    immediateAction: 'EMERGENCY SURGERY REQUIRED. Call 112/911 immediately. Life-threatening condition.',
    redFlags: ['sudden onset severe abdominal pain', 'rigid abdomen', 'shock', 'free air under diaphragm'],
    differentialDiagnosis: ['acute-pancreatitis', 'mesenteric-ischemia', 'ruptured-aaa'],
    specialists: ['general-surgeon', 'emergency-medicine'],
    prevalence: 'uncommon',
    crisis: true
  },

  'acute-pancreatitis': {
    id: 'acute-pancreatitis',
    name: 'Acute Pancreatitis',
    nameAr: 'التهاب البنكرياس الحاد',
    nameDe: 'Akute Pankreatitis',
    nameFr: 'Pancréatite aiguë',
    icd11: 'DC31.0',
    snomed: '197456007',
    category: 'surgical-emergency',
    urgency: 'emergency',
    primarySymptoms: ['abdominal-pain-epigastric', 'abdominal-pain-radiating-back', 'nausea'],
    secondarySymptoms: ['vomiting', 'fever', 'tachycardia', 'jaundice'],
    associatedSymptoms: ['abdominal-tenderness', 'ileus', 'cullen-sign', 'grey-turner-sign'],
    riskFactors: ['gallstones', 'alcohol', 'hypertriglyceridemia', 'medications', 'ercp'],
    ageGroups: ['adult', 'elderly'],
    genderPrevalence: 'equal',
    description: 'Acute inflammation of the pancreas that can range from mild to life-threatening.',
    immediateAction: 'Hospital admission required. NPO, IV fluids, pain management, treat underlying cause.',
    redFlags: ['severe pain not responding to medication', 'respiratory distress', 'shock', 'organ failure'],
    differentialDiagnosis: ['peptic-ulcer', 'cholecystitis', 'mesenteric-ischemia', 'aortic-dissection'],
    specialists: ['gastroenterologist', 'general-surgeon', 'intensivist'],
    prevalence: 'common'
  },

  'incarcerated-hernia': {
    id: 'incarcerated-hernia',
    name: 'Incarcerated Hernia',
    nameAr: 'فتق منحصر',
    nameDe: 'Eingeklemmter Bruch',
    nameFr: 'Hernie incarcérée',
    icd11: 'LB10.1',
    snomed: '79070009',
    category: 'surgical-emergency',
    urgency: 'emergency',
    primarySymptoms: ['groin-swelling-painful', 'abdominal-pain', 'nausea'],
    secondarySymptoms: ['vomiting', 'constipation', 'irreducible-hernia'],
    associatedSymptoms: ['fever', 'abdominal-distension', 'tachycardia'],
    riskFactors: ['previous-hernia', 'heavy-lifting', 'chronic-cough', 'obesity'],
    ageGroups: ['adult', 'elderly'],
    genderPrevalence: 'male',
    description: 'Hernia contents trapped and unable to be reduced, risking strangulation and bowel necrosis.',
    immediateAction: 'Emergency surgery required if manual reduction fails. Risk of bowel strangulation.',
    redFlags: ['severe pain', 'skin color change over hernia', 'fever', 'signs of obstruction'],
    differentialDiagnosis: ['strangulated-hernia', 'lymphadenopathy', 'testicular-torsion', 'femoral-aneurysm'],
    specialists: ['general-surgeon'],
    prevalence: 'common',
    crisis: true
  },

  'testicular-torsion': {
    id: 'testicular-torsion',
    name: 'Testicular Torsion',
    nameAr: 'التواء الخصية',
    nameDe: 'Hodentorsion',
    nameFr: 'Torsion testiculaire',
    icd11: 'GB05.1',
    snomed: '44643003',
    category: 'surgical-emergency',
    urgency: 'emergency',
    primarySymptoms: ['testicular-pain-sudden', 'testicular-swelling', 'nausea'],
    secondarySymptoms: ['vomiting', 'abdominal-pain-lower', 'elevated-testis'],
    associatedSymptoms: ['absent-cremasteric-reflex', 'scrotal-redness'],
    riskFactors: ['age-12-18', 'previous-torsion', 'bell-clapper-deformity'],
    ageGroups: ['child', 'adolescent', 'adult'],
    genderPrevalence: 'male',
    description: 'Twisting of the spermatic cord cutting off blood supply to the testicle - surgical emergency.',
    immediateAction: 'EMERGENCY SURGERY within 6 hours to save the testicle. Call 112/911 immediately.',
    redFlags: ['sudden severe testicular pain', 'high-riding testis', 'absent cremasteric reflex'],
    differentialDiagnosis: ['epididymitis', 'torsion-appendix-testis', 'orchitis', 'trauma'],
    specialists: ['urologist', 'emergency-medicine'],
    prevalence: 'uncommon',
    crisis: true,
    typicalDuration: 'Surgery within 6 hours critical'
  },

  'ruptured-ectopic-pregnancy': {
    id: 'ruptured-ectopic-pregnancy',
    name: 'Ruptured Ectopic Pregnancy',
    nameAr: 'حمل خارج الرحم ممزق',
    nameDe: 'Rupturierte Eileiterschwangerschaft',
    nameFr: 'Grossesse extra-utérine rompue',
    icd11: 'JA03',
    snomed: '34801009',
    category: 'surgical-emergency',
    urgency: 'emergency',
    primarySymptoms: ['abdominal-pain-sudden-severe', 'vaginal-bleeding', 'shoulder-tip-pain'],
    secondarySymptoms: ['dizziness', 'syncope', 'hypotension', 'tachycardia'],
    associatedSymptoms: ['missed-period', 'positive-pregnancy-test', 'shock'],
    riskFactors: ['previous-ectopic', 'pid', 'tubal-surgery', 'iud', 'infertility-treatment'],
    ageGroups: ['adult'],
    genderPrevalence: 'female',
    description: 'Life-threatening emergency when a pregnancy implanted outside the uterus ruptures.',
    immediateAction: 'CALL 112/911 IMMEDIATELY. Life-threatening hemorrhage. Emergency surgery required.',
    redFlags: ['sudden severe abdominal pain with positive pregnancy test', 'signs of shock', 'shoulder pain'],
    differentialDiagnosis: ['ovarian-cyst-rupture', 'miscarriage', 'appendicitis', 'ovarian-torsion'],
    specialists: ['obgyn', 'emergency-medicine'],
    prevalence: 'uncommon',
    crisis: true
  },

  'aortic-dissection': {
    id: 'aortic-dissection',
    name: 'Aortic Dissection',
    nameAr: 'تسلخ الشريان الأبهري',
    nameDe: 'Aortendissektion',
    nameFr: 'Dissection aortique',
    icd11: 'BA81',
    snomed: '308546005',
    category: 'surgical-emergency',
    urgency: 'emergency',
    primarySymptoms: ['chest-pain-tearing', 'back-pain-sudden', 'pulse-deficit'],
    secondarySymptoms: ['hypotension', 'syncope', 'neurological-deficit', 'aortic-regurgitation'],
    associatedSymptoms: ['blood-pressure-differential', 'stroke-symptoms', 'limb-ischemia'],
    riskFactors: ['hypertension', 'marfan-syndrome', 'bicuspid-aortic-valve', 'cocaine-use', 'pregnancy'],
    ageGroups: ['adult', 'elderly'],
    genderPrevalence: 'male',
    description: 'Tear in the aortic wall allowing blood to flow between layers - immediately life-threatening.',
    immediateAction: 'CALL 112/911. Highest emergency. Type A requires immediate surgery. Type B may be managed medically.',
    redFlags: ['sudden severe chest/back pain', 'tearing quality', 'pulse differences between arms', 'stroke symptoms'],
    differentialDiagnosis: ['myocardial-infarction', 'pulmonary-embolism', 'pericarditis', 'musculoskeletal-pain'],
    specialists: ['cardiothoracic-surgeon', 'vascular-surgeon', 'emergency-medicine'],
    prevalence: 'rare',
    crisis: true
  },

  'ruptured-aaa': {
    id: 'ruptured-aaa',
    name: 'Ruptured Abdominal Aortic Aneurysm',
    nameAr: 'تمدد الشريان الأورطي البطني الممزق',
    nameDe: 'Rupturiertes Bauchaortenaneurysma',
    nameFr: 'Rupture d\'anévrisme de l\'aorte abdominale',
    icd11: 'BA82.1',
    snomed: '233936003',
    category: 'surgical-emergency',
    urgency: 'emergency',
    primarySymptoms: ['abdominal-pain-sudden-severe', 'back-pain', 'pulsatile-abdominal-mass'],
    secondarySymptoms: ['hypotension', 'syncope', 'flank-ecchymosis'],
    associatedSymptoms: ['shock', 'altered-consciousness', 'limb-ischemia'],
    riskFactors: ['age>65', 'male', 'smoking', 'hypertension', 'family-history', 'atherosclerosis'],
    ageGroups: ['elderly'],
    genderPrevalence: 'male',
    description: 'Catastrophic rupture of an abdominal aortic aneurysm with massive internal bleeding.',
    immediateAction: 'CALL 112/911 IMMEDIATELY. Mortality rate 80-90% without emergency surgery.',
    redFlags: ['sudden severe abdominal/back pain', 'pulsatile mass', 'hypotension', 'known AAA'],
    differentialDiagnosis: ['renal-colic', 'acute-pancreatitis', 'mesenteric-ischemia'],
    specialists: ['vascular-surgeon', 'emergency-medicine'],
    prevalence: 'rare',
    crisis: true
  },

  // ORTHOPEDIC EMERGENCIES
  'open-fracture': {
    id: 'open-fracture',
    name: 'Open (Compound) Fracture',
    nameAr: 'كسر مفتوح',
    nameDe: 'Offene Fraktur',
    nameFr: 'Fracture ouverte',
    icd11: 'NB20',
    snomed: '397181002',
    category: 'orthopedic-emergency',
    urgency: 'emergency',
    primarySymptoms: ['bone-visible', 'wound-with-fracture', 'severe-pain'],
    secondarySymptoms: ['bleeding', 'deformity', 'inability-move-limb'],
    associatedSymptoms: ['swelling', 'numbness', 'pallor-of-limb'],
    riskFactors: ['trauma', 'high-energy-injury', 'osteoporosis'],
    ageGroups: ['child', 'adolescent', 'adult', 'elderly'],
    genderPrevalence: 'male',
    description: 'Fracture with skin break and bone exposure - high risk of infection and complications.',
    immediateAction: 'Emergency care immediately. Do not push bone back. Cover with clean dressing. Antibiotics within 1 hour.',
    redFlags: ['bone exposure', 'active bleeding', 'signs of vascular compromise', 'compartment syndrome signs'],
    differentialDiagnosis: ['closed-fracture', 'dislocation', 'soft-tissue-injury'],
    specialists: ['orthopedic-surgeon', 'trauma-surgeon'],
    prevalence: 'uncommon',
    crisis: true
  },

  'compartment-syndrome': {
    id: 'compartment-syndrome',
    name: 'Acute Compartment Syndrome',
    nameAr: 'متلازمة الحيز الحادة',
    nameDe: 'Akutes Kompartmentsyndrom',
    nameFr: 'Syndrome de loge aigu',
    icd11: 'FB83.0',
    snomed: '111245009',
    category: 'orthopedic-emergency',
    urgency: 'emergency',
    primarySymptoms: ['pain-out-of-proportion', 'pain-with-passive-stretch', 'paresthesia'],
    secondarySymptoms: ['swelling-tense', 'weakness', 'pallor'],
    associatedSymptoms: ['pulselessness', 'paralysis'],
    riskFactors: ['fracture', 'crush-injury', 'tight-cast', 'burns', 'anticoagulation'],
    ageGroups: ['child', 'adolescent', 'adult', 'elderly'],
    genderPrevalence: 'equal',
    description: 'Increased pressure within a muscle compartment compromising blood flow - requires emergency fasciotomy.',
    immediateAction: 'EMERGENCY SURGERY (fasciotomy) required within 6 hours to prevent permanent muscle/nerve damage.',
    redFlags: ['6 Ps: Pain, Pressure, Paresthesia, Pallor, Paralysis, Pulselessness'],
    differentialDiagnosis: ['deep-vein-thrombosis', 'cellulitis', 'muscle-strain'],
    specialists: ['orthopedic-surgeon', 'trauma-surgeon'],
    prevalence: 'uncommon',
    crisis: true
  },

  'septic-arthritis': {
    id: 'septic-arthritis',
    name: 'Septic Arthritis',
    nameAr: 'التهاب المفاصل الإنتاني',
    nameDe: 'Septische Arthritis',
    nameFr: 'Arthrite septique',
    icd11: 'FA20',
    snomed: '156461000',
    category: 'orthopedic-emergency',
    urgency: 'emergency',
    primarySymptoms: ['joint-pain-severe', 'joint-swelling', 'fever'],
    secondarySymptoms: ['joint-warmth', 'joint-redness', 'inability-bear-weight'],
    associatedSymptoms: ['chills', 'malaise', 'decreased-range-motion'],
    riskFactors: ['joint-replacement', 'immunosuppression', 'diabetes', 'iv-drug-use', 'recent-joint-injection'],
    ageGroups: ['infant', 'child', 'adult', 'elderly'],
    genderPrevalence: 'equal',
    description: 'Bacterial infection within a joint requiring urgent drainage to prevent cartilage destruction.',
    immediateAction: 'Emergency joint aspiration and IV antibiotics. Surgical drainage often required.',
    redFlags: ['acute monoarthritis with fever', 'inability to move joint', 'systemic illness'],
    differentialDiagnosis: ['gout', 'pseudogout', 'reactive-arthritis', 'rheumatoid-flare'],
    specialists: ['orthopedic-surgeon', 'rheumatologist', 'infectious-disease'],
    prevalence: 'uncommon',
    crisis: true
  },

  'cauda-equina-syndrome': {
    id: 'cauda-equina-syndrome',
    name: 'Cauda Equina Syndrome',
    nameAr: 'متلازمة ذيل الفرس',
    nameDe: 'Cauda-Equina-Syndrom',
    nameFr: 'Syndrome de la queue de cheval',
    icd11: 'FA82',
    snomed: '192970008',
    category: 'neurosurgical-emergency',
    urgency: 'emergency',
    primarySymptoms: ['back-pain-severe', 'saddle-anesthesia', 'urinary-retention'],
    secondarySymptoms: ['fecal-incontinence', 'leg-weakness-bilateral', 'sexual-dysfunction'],
    associatedSymptoms: ['sciatica-bilateral', 'reduced-anal-tone'],
    riskFactors: ['disc-herniation', 'spinal-stenosis', 'trauma', 'tumor', 'abscess'],
    ageGroups: ['adult', 'elderly'],
    genderPrevalence: 'equal',
    description: 'Compression of cauda equina nerve roots causing neurological emergency requiring urgent decompression.',
    immediateAction: 'EMERGENCY MRI and surgery within 24-48 hours. Permanent damage if delayed.',
    redFlags: ['saddle anesthesia', 'bladder/bowel dysfunction', 'bilateral leg weakness', 'progressive symptoms'],
    differentialDiagnosis: ['disc-herniation', 'spinal-cord-compression', 'conus-medullaris-syndrome'],
    specialists: ['neurosurgeon', 'spine-surgeon'],
    prevalence: 'rare',
    crisis: true
  },

  'necrotizing-fasciitis': {
    id: 'necrotizing-fasciitis',
    name: 'Necrotizing Fasciitis',
    nameAr: 'التهاب اللفافة الناخر',
    nameDe: 'Nekrotisierende Fasziitis',
    nameFr: 'Fasciite nécrosante',
    icd11: 'DB90.1',
    snomed: '52486002',
    category: 'surgical-emergency',
    urgency: 'emergency',
    primarySymptoms: ['pain-severe-out-of-proportion', 'rapidly-spreading-erythema', 'fever'],
    secondarySymptoms: ['skin-necrosis', 'crepitus', 'bullae', 'systemic-toxicity'],
    associatedSymptoms: ['hypotension', 'altered-mental-status', 'multi-organ-failure'],
    riskFactors: ['diabetes', 'immunosuppression', 'obesity', 'recent-surgery', 'iv-drug-use'],
    ageGroups: ['adult', 'elderly'],
    genderPrevalence: 'equal',
    description: 'Rapidly progressive, life-threatening soft tissue infection requiring emergency debridement.',
    immediateAction: 'EMERGENCY SURGERY within hours. IV antibiotics. ICU admission. Mortality 20-40%.',
    redFlags: ['pain out of proportion', 'rapid progression', 'skin changes', 'crepitus', 'sepsis'],
    differentialDiagnosis: ['cellulitis', 'gas-gangrene', 'pyomyositis', 'erysipelas'],
    specialists: ['general-surgeon', 'plastic-surgeon', 'infectious-disease'],
    prevalence: 'rare',
    crisis: true
  },

  // TRAUMA CONDITIONS
  'tension-pneumothorax': {
    id: 'tension-pneumothorax',
    name: 'Tension Pneumothorax',
    nameAr: 'استرواح الصدر الضاغط',
    nameDe: 'Spannungspneumothorax',
    nameFr: 'Pneumothorax sous tension',
    icd11: 'CB23.0',
    snomed: '233626009',
    category: 'trauma-emergency',
    urgency: 'emergency',
    primarySymptoms: ['severe-respiratory-distress', 'hypotension', 'tracheal-deviation'],
    secondarySymptoms: ['absent-breath-sounds', 'distended-neck-veins', 'cyanosis'],
    associatedSymptoms: ['chest-pain', 'tachycardia', 'decreased-consciousness'],
    riskFactors: ['chest-trauma', 'mechanical-ventilation', 'central-line-placement', 'copd', 'asthma'],
    ageGroups: ['child', 'adolescent', 'adult', 'elderly'],
    genderPrevalence: 'equal',
    description: 'Life-threatening accumulation of air in pleural space causing cardiovascular collapse.',
    immediateAction: 'IMMEDIATE needle decompression followed by chest tube. Do not delay for imaging.',
    redFlags: ['respiratory distress', 'hypotension', 'tracheal deviation', 'distended neck veins'],
    differentialDiagnosis: ['cardiac-tamponade', 'massive-hemothorax', 'simple-pneumothorax'],
    specialists: ['trauma-surgeon', 'emergency-medicine'],
    prevalence: 'uncommon',
    crisis: true
  },

  'cardiac-tamponade': {
    id: 'cardiac-tamponade',
    name: 'Cardiac Tamponade',
    nameAr: 'الدكاك القلبي',
    nameDe: 'Herzbeuteltamponade',
    nameFr: 'Tamponnade cardiaque',
    icd11: 'BB23',
    snomed: '35304003',
    category: 'cardiac-emergency',
    urgency: 'emergency',
    primarySymptoms: ['hypotension', 'distended-neck-veins', 'muffled-heart-sounds'],
    secondarySymptoms: ['tachycardia', 'pulsus-paradoxus', 'dyspnea'],
    associatedSymptoms: ['anxiety', 'chest-discomfort', 'altered-consciousness'],
    riskFactors: ['chest-trauma', 'pericarditis', 'malignancy', 'post-cardiac-surgery', 'uremia'],
    ageGroups: ['adult', 'elderly'],
    genderPrevalence: 'equal',
    description: 'Life-threatening compression of the heart by fluid in the pericardial space.',
    immediateAction: 'EMERGENCY pericardiocentesis or surgical drainage. Beck\'s triad: hypotension, JVD, muffled sounds.',
    redFlags: ['Beck\'s triad', 'pulsus paradoxus >10mmHg', 'electrical alternans on ECG'],
    differentialDiagnosis: ['tension-pneumothorax', 'pulmonary-embolism', 'right-heart-failure'],
    specialists: ['cardiothoracic-surgeon', 'cardiologist', 'emergency-medicine'],
    prevalence: 'uncommon',
    crisis: true
  },

  'splenic-rupture': {
    id: 'splenic-rupture',
    name: 'Splenic Rupture',
    nameAr: 'تمزق الطحال',
    nameDe: 'Milzruptur',
    nameFr: 'Rupture splénique',
    icd11: 'NA87.2',
    snomed: '60634008',
    category: 'trauma-emergency',
    urgency: 'emergency',
    primarySymptoms: ['left-upper-quadrant-pain', 'left-shoulder-pain', 'hypotension'],
    secondarySymptoms: ['abdominal-rigidity', 'tachycardia', 'pallor'],
    associatedSymptoms: ['signs-of-shock', 'abdominal-distension'],
    riskFactors: ['abdominal-trauma', 'splenomegaly', 'infectious-mononucleosis', 'anticoagulation'],
    ageGroups: ['child', 'adolescent', 'adult'],
    genderPrevalence: 'equal',
    description: 'Rupture of the spleen causing internal hemorrhage, often from blunt abdominal trauma.',
    immediateAction: 'Emergency surgery may be required. Blood transfusion. Some cases managed conservatively.',
    redFlags: ['hemodynamic instability', 'peritonitis', 'ongoing transfusion requirements'],
    differentialDiagnosis: ['liver-laceration', 'hollow-viscus-injury', 'retroperitoneal-hematoma'],
    specialists: ['trauma-surgeon', 'general-surgeon'],
    prevalence: 'uncommon',
    crisis: true
  }
};

// ============================================================================
// CARDIOVASCULAR CONDITIONS (120+)
// ============================================================================

export const CARDIOVASCULAR_CONDITIONS: Record<string, MedicalCondition> = {
  'unstable-angina': {
    id: 'unstable-angina',
    name: 'Unstable Angina',
    nameAr: 'الذبحة الصدرية غير المستقرة',
    nameDe: 'Instabile Angina pectoris',
    nameFr: 'Angor instable',
    icd11: 'BA80.0',
    snomed: '25106000',
    category: 'cardiovascular',
    urgency: 'emergency',
    primarySymptoms: ['chest-pain-new-onset', 'chest-pain-at-rest', 'chest-pain-increasing'],
    secondarySymptoms: ['shortness-breath', 'sweating', 'nausea'],
    associatedSymptoms: ['fatigue', 'dizziness', 'anxiety'],
    riskFactors: ['coronary-artery-disease', 'diabetes', 'hypertension', 'smoking', 'hyperlipidemia'],
    ageGroups: ['adult', 'elderly'],
    genderPrevalence: 'male',
    description: 'Chest pain that occurs at rest or with minimal exertion, indicating impending heart attack.',
    immediateAction: 'Call 112/911. Aspirin if not allergic. Hospital admission for monitoring and possible intervention.',
    redFlags: ['new or worsening chest pain', 'pain at rest', 'pain not responding to nitroglycerin'],
    differentialDiagnosis: ['myocardial-infarction', 'stable-angina', 'gerd', 'costochondritis'],
    specialists: ['cardiologist', 'emergency-medicine'],
    prevalence: 'common'
  },

  'atrial-fibrillation': {
    id: 'atrial-fibrillation',
    name: 'Atrial Fibrillation',
    nameAr: 'الرجفان الأذيني',
    nameDe: 'Vorhofflimmern',
    nameFr: 'Fibrillation auriculaire',
    icd11: 'BC81.0',
    snomed: '49436004',
    category: 'cardiovascular',
    urgency: 'urgent',
    primarySymptoms: ['palpitations-irregular', 'fatigue', 'shortness-breath'],
    secondarySymptoms: ['dizziness', 'chest-discomfort', 'exercise-intolerance'],
    associatedSymptoms: ['anxiety', 'weakness', 'syncope'],
    riskFactors: ['hypertension', 'heart-failure', 'valvular-disease', 'thyroid-disease', 'obesity', 'alcohol'],
    ageGroups: ['adult', 'elderly'],
    genderPrevalence: 'male',
    description: 'Irregular heart rhythm originating in the atria, increasing stroke risk 5-fold.',
    immediateAction: 'Seek medical evaluation. Rate control and anticoagulation often needed. Stroke prevention is key.',
    redFlags: ['rapid heart rate >150', 'chest pain', 'severe shortness of breath', 'syncope'],
    differentialDiagnosis: ['atrial-flutter', 'svt', 'multifocal-atrial-tachycardia'],
    specialists: ['cardiologist', 'electrophysiologist'],
    prevalence: 'common'
  },

  'heart-failure-acute': {
    id: 'heart-failure-acute',
    name: 'Acute Heart Failure',
    nameAr: 'قصور القلب الحاد',
    nameDe: 'Akute Herzinsuffizienz',
    nameFr: 'Insuffisance cardiaque aiguë',
    icd11: 'BD10',
    snomed: '56675007',
    category: 'cardiovascular',
    urgency: 'emergency',
    primarySymptoms: ['shortness-breath-severe', 'orthopnea', 'leg-swelling-bilateral'],
    secondarySymptoms: ['paroxysmal-nocturnal-dyspnea', 'fatigue', 'rapid-weight-gain'],
    associatedSymptoms: ['cough-pink-frothy', 'wheezing', 'cold-extremities'],
    riskFactors: ['coronary-artery-disease', 'hypertension', 'valvular-disease', 'cardiomyopathy', 'diabetes'],
    ageGroups: ['adult', 'elderly'],
    genderPrevalence: 'equal',
    description: 'Sudden worsening of heart failure causing fluid backup in lungs and body.',
    immediateAction: 'Emergency department. Diuretics, oxygen, possibly non-invasive ventilation.',
    redFlags: ['severe respiratory distress', 'hypoxia', 'altered mental status', 'cardiogenic shock'],
    differentialDiagnosis: ['pneumonia', 'copd-exacerbation', 'pulmonary-embolism', 'acute-coronary-syndrome'],
    specialists: ['cardiologist', 'emergency-medicine'],
    prevalence: 'common'
  },

  'pulmonary-embolism': {
    id: 'pulmonary-embolism',
    name: 'Pulmonary Embolism',
    nameAr: 'الانسداد الرئوي',
    nameDe: 'Lungenembolie',
    nameFr: 'Embolie pulmonaire',
    icd11: 'BB00',
    snomed: '59282003',
    category: 'cardiovascular',
    urgency: 'emergency',
    primarySymptoms: ['shortness-breath-sudden', 'chest-pain-pleuritic', 'tachycardia'],
    secondarySymptoms: ['cough', 'hemoptysis', 'leg-swelling-unilateral'],
    associatedSymptoms: ['syncope', 'fever', 'anxiety', 'diaphoresis'],
    riskFactors: ['recent-surgery', 'immobility', 'cancer', 'pregnancy', 'oral-contraceptives', 'dvt', 'obesity'],
    ageGroups: ['adult', 'elderly'],
    genderPrevalence: 'female',
    description: 'Blood clot blocking pulmonary arteries, potentially life-threatening.',
    immediateAction: 'Emergency CT angiography. Anticoagulation. Massive PE may need thrombolysis.',
    redFlags: ['syncope', 'hypotension', 'severe hypoxia', 'right heart strain'],
    differentialDiagnosis: ['pneumonia', 'myocardial-infarction', 'pneumothorax', 'aortic-dissection'],
    specialists: ['pulmonologist', 'cardiologist', 'hematologist'],
    prevalence: 'common',
    crisis: true
  },

  'deep-vein-thrombosis': {
    id: 'deep-vein-thrombosis',
    name: 'Deep Vein Thrombosis',
    nameAr: 'تخثر الوريد العميق',
    nameDe: 'Tiefe Venenthrombose',
    nameFr: 'Thrombose veineuse profonde',
    icd11: 'BD70',
    snomed: '128053003',
    category: 'cardiovascular',
    urgency: 'urgent',
    primarySymptoms: ['leg-swelling-unilateral', 'leg-pain', 'leg-warmth'],
    secondarySymptoms: ['leg-redness', 'distended-superficial-veins', 'calf-tenderness'],
    associatedSymptoms: ['fever', 'pitting-edema'],
    riskFactors: ['immobility', 'surgery', 'cancer', 'pregnancy', 'oral-contraceptives', 'obesity', 'smoking'],
    ageGroups: ['adult', 'elderly'],
    genderPrevalence: 'equal',
    description: 'Blood clot in deep veins, usually legs, with risk of pulmonary embolism.',
    immediateAction: 'Urgent ultrasound. Start anticoagulation if confirmed. Monitor for PE symptoms.',
    redFlags: ['massive leg swelling', 'signs of PE', 'phlegmasia cerulea dolens'],
    differentialDiagnosis: ['cellulitis', 'muscle-strain', 'baker-cyst-rupture', 'superficial-thrombophlebitis'],
    specialists: ['vascular-medicine', 'hematologist'],
    prevalence: 'common'
  },

  'hypertensive-crisis': {
    id: 'hypertensive-crisis',
    name: 'Hypertensive Crisis',
    nameAr: 'أزمة ارتفاع ضغط الدم',
    nameDe: 'Hypertensive Krise',
    nameFr: 'Crise hypertensive',
    icd11: 'BA03',
    snomed: '706882009',
    category: 'cardiovascular',
    urgency: 'emergency',
    primarySymptoms: ['headache-severe', 'chest-pain', 'shortness-breath'],
    secondarySymptoms: ['vision-changes', 'nausea', 'confusion'],
    associatedSymptoms: ['nosebleed', 'anxiety', 'numbness'],
    riskFactors: ['uncontrolled-hypertension', 'medication-noncompliance', 'cocaine', 'pheochromocytoma'],
    ageGroups: ['adult', 'elderly'],
    genderPrevalence: 'equal',
    description: 'Severely elevated blood pressure (>180/120) with or without target organ damage.',
    immediateAction: 'Emergency if organ damage (emergency), urgent care if not (urgency). IV medications may be needed.',
    redFlags: ['BP >180/120 with symptoms', 'chest pain', 'neurological symptoms', 'visual changes'],
    differentialDiagnosis: ['anxiety', 'pain', 'pheochromocytoma', 'renal-artery-stenosis'],
    specialists: ['cardiologist', 'nephrologist', 'emergency-medicine'],
    prevalence: 'common'
  },

  'infective-endocarditis': {
    id: 'infective-endocarditis',
    name: 'Infective Endocarditis',
    nameAr: 'التهاب الشغاف المعدي',
    nameDe: 'Infektiöse Endokarditis',
    nameFr: 'Endocardite infectieuse',
    icd11: 'BB40',
    snomed: '233843008',
    category: 'cardiovascular',
    urgency: 'emergency',
    primarySymptoms: ['fever', 'new-heart-murmur', 'fatigue'],
    secondarySymptoms: ['night-sweats', 'weight-loss', 'petechiae'],
    associatedSymptoms: ['splinter-hemorrhages', 'janeway-lesions', 'osler-nodes', 'embolic-phenomena'],
    riskFactors: ['prosthetic-valve', 'congenital-heart-disease', 'iv-drug-use', 'poor-dental-hygiene'],
    ageGroups: ['adult', 'elderly'],
    genderPrevalence: 'male',
    description: 'Infection of heart valves, often bacterial, requiring prolonged antibiotics and sometimes surgery.',
    immediateAction: 'Blood cultures, echocardiogram. IV antibiotics for 4-6 weeks. Surgery if valve destruction.',
    redFlags: ['embolic events', 'heart failure', 'persistent fever on antibiotics', 'valve destruction'],
    differentialDiagnosis: ['fever-of-unknown-origin', 'rheumatic-fever', 'sle', 'atrial-myxoma'],
    specialists: ['cardiologist', 'infectious-disease', 'cardiothoracic-surgeon'],
    prevalence: 'uncommon'
  },

  'pericarditis-acute': {
    id: 'pericarditis-acute',
    name: 'Acute Pericarditis',
    nameAr: 'التهاب التامور الحاد',
    nameDe: 'Akute Perikarditis',
    nameFr: 'Péricardite aiguë',
    icd11: 'BB20',
    snomed: '3238004',
    category: 'cardiovascular',
    urgency: 'urgent',
    primarySymptoms: ['chest-pain-sharp', 'chest-pain-worse-lying-flat', 'chest-pain-better-leaning-forward'],
    secondarySymptoms: ['fever', 'pericardial-friction-rub', 'dyspnea'],
    associatedSymptoms: ['malaise', 'cough', 'hiccups'],
    riskFactors: ['viral-infection', 'post-mi', 'uremia', 'autoimmune-disease', 'malignancy', 'post-cardiac-surgery'],
    ageGroups: ['adult', 'elderly'],
    genderPrevalence: 'male',
    description: 'Inflammation of the pericardium causing characteristic chest pain and ECG changes.',
    immediateAction: 'ECG and echocardiogram. NSAIDs/colchicine. Monitor for tamponade.',
    redFlags: ['signs of tamponade', 'hemodynamic instability', 'large effusion', 'purulent pericarditis'],
    differentialDiagnosis: ['myocardial-infarction', 'pulmonary-embolism', 'pleuritis', 'costochondritis'],
    specialists: ['cardiologist'],
    prevalence: 'uncommon'
  }
};

// ============================================================================
// RESPIRATORY CONDITIONS (100+)
// ============================================================================

export const RESPIRATORY_CONDITIONS: Record<string, MedicalCondition> = {
  'pneumonia-community': {
    id: 'pneumonia-community',
    name: 'Community-Acquired Pneumonia',
    nameAr: 'الالتهاب الرئوي المكتسب من المجتمع',
    nameDe: 'Ambulant erworbene Pneumonie',
    nameFr: 'Pneumonie communautaire',
    icd11: 'CA40',
    snomed: '385093006',
    category: 'respiratory',
    urgency: 'urgent',
    primarySymptoms: ['cough-productive', 'fever', 'shortness-breath'],
    secondarySymptoms: ['chest-pain-pleuritic', 'chills', 'fatigue'],
    associatedSymptoms: ['tachypnea', 'tachycardia', 'confusion-elderly'],
    riskFactors: ['age>65', 'smoking', 'copd', 'immunosuppression', 'alcoholism', 'recent-viral-infection'],
    ageGroups: ['infant', 'child', 'adult', 'elderly'],
    genderPrevalence: 'equal',
    description: 'Lung infection acquired outside hospital, ranging from mild to life-threatening.',
    immediateAction: 'Chest X-ray. Antibiotics based on severity. Hospitalization if CURB-65 score high.',
    redFlags: ['severe hypoxia', 'confusion', 'multilobar involvement', 'sepsis', 'respiratory failure'],
    differentialDiagnosis: ['bronchitis', 'pulmonary-embolism', 'tuberculosis', 'lung-cancer'],
    specialists: ['pulmonologist', 'infectious-disease'],
    prevalence: 'common'
  },

  'asthma-acute': {
    id: 'asthma-acute',
    name: 'Acute Asthma Exacerbation',
    nameAr: 'نوبة الربو الحادة',
    nameDe: 'Akuter Asthmaanfall',
    nameFr: 'Exacerbation aiguë d\'asthme',
    icd11: 'CA23',
    snomed: '304527002',
    category: 'respiratory',
    urgency: 'urgent',
    primarySymptoms: ['wheezing', 'shortness-breath', 'chest-tightness'],
    secondarySymptoms: ['cough', 'tachypnea', 'use-accessory-muscles'],
    associatedSymptoms: ['anxiety', 'difficulty-speaking', 'pale-diaphoretic'],
    riskFactors: ['known-asthma', 'recent-infection', 'allergen-exposure', 'medication-noncompliance', 'cold-air'],
    ageGroups: ['child', 'adolescent', 'adult'],
    genderPrevalence: 'equal',
    description: 'Acute worsening of asthma symptoms requiring immediate bronchodilator therapy.',
    immediateAction: 'Use rescue inhaler. Seek emergency care if no improvement or severe symptoms.',
    redFlags: ['silent chest', 'cyanosis', 'altered mental status', 'peak flow <25% predicted', 'unable to speak'],
    differentialDiagnosis: ['copd-exacerbation', 'anaphylaxis', 'foreign-body', 'heart-failure'],
    specialists: ['pulmonologist', 'allergist', 'emergency-medicine'],
    prevalence: 'common'
  },

  'copd-exacerbation': {
    id: 'copd-exacerbation',
    name: 'COPD Exacerbation',
    nameAr: 'تفاقم مرض الانسداد الرئوي المزمن',
    nameDe: 'COPD-Exazerbation',
    nameFr: 'Exacerbation de BPCO',
    icd11: 'CA22',
    snomed: '195951007',
    category: 'respiratory',
    urgency: 'urgent',
    primarySymptoms: ['shortness-breath-worsening', 'increased-sputum', 'sputum-color-change'],
    secondarySymptoms: ['wheezing', 'chest-tightness', 'cough-worsening'],
    associatedSymptoms: ['fatigue', 'fever', 'ankle-swelling'],
    riskFactors: ['smoking-history', 'air-pollution', 'respiratory-infection', 'cold-weather'],
    ageGroups: ['adult', 'elderly'],
    genderPrevalence: 'equal',
    description: 'Acute worsening of COPD symptoms beyond normal day-to-day variation.',
    immediateAction: 'Bronchodilators, steroids, antibiotics if purulent sputum. Oxygen if hypoxic.',
    redFlags: ['severe hypoxia', 'hypercapnia', 'altered mental status', 'hemodynamic instability'],
    differentialDiagnosis: ['pneumonia', 'heart-failure', 'pulmonary-embolism', 'pneumothorax'],
    specialists: ['pulmonologist'],
    prevalence: 'common'
  },

  'spontaneous-pneumothorax': {
    id: 'spontaneous-pneumothorax',
    name: 'Spontaneous Pneumothorax',
    nameAr: 'استرواح الصدر التلقائي',
    nameDe: 'Spontanpneumothorax',
    nameFr: 'Pneumothorax spontané',
    icd11: 'CB21',
    snomed: '36118008',
    category: 'respiratory',
    urgency: 'urgent',
    primarySymptoms: ['chest-pain-sudden', 'shortness-breath-sudden', 'decreased-breath-sounds'],
    secondarySymptoms: ['tachycardia', 'tachypnea', 'hyperresonance'],
    associatedSymptoms: ['anxiety', 'cough'],
    riskFactors: ['tall-thin-male', 'smoking', 'copd', 'marfan-syndrome', 'previous-pneumothorax'],
    ageGroups: ['adolescent', 'adult'],
    genderPrevalence: 'male',
    description: 'Air leak into pleural space without trauma, causing lung collapse.',
    immediateAction: 'Chest X-ray. Small may observe. Large requires chest tube.',
    redFlags: ['tension pneumothorax signs', 'bilateral', 'hemodynamic instability'],
    differentialDiagnosis: ['pulmonary-embolism', 'myocardial-infarction', 'pleuritis', 'musculoskeletal'],
    specialists: ['pulmonologist', 'thoracic-surgeon'],
    prevalence: 'uncommon'
  },

  'acute-respiratory-distress-syndrome': {
    id: 'acute-respiratory-distress-syndrome',
    name: 'Acute Respiratory Distress Syndrome (ARDS)',
    nameAr: 'متلازمة الضائقة التنفسية الحادة',
    nameDe: 'Akutes Atemnotsyndrom',
    nameFr: 'Syndrome de détresse respiratoire aiguë',
    icd11: 'CB00',
    snomed: '67782005',
    category: 'respiratory',
    urgency: 'emergency',
    primarySymptoms: ['severe-hypoxia', 'bilateral-infiltrates', 'respiratory-failure'],
    secondarySymptoms: ['tachypnea', 'cyanosis', 'use-accessory-muscles'],
    associatedSymptoms: ['confusion', 'tachycardia', 'multi-organ-dysfunction'],
    riskFactors: ['sepsis', 'pneumonia', 'aspiration', 'trauma', 'pancreatitis', 'transfusion'],
    ageGroups: ['adult', 'elderly'],
    genderPrevalence: 'equal',
    description: 'Severe inflammatory lung injury causing profound hypoxemia requiring ICU care.',
    immediateAction: 'ICU admission. Mechanical ventilation with lung-protective strategy. Treat underlying cause.',
    redFlags: ['P/F ratio <100', 'refractory hypoxemia', 'multi-organ failure'],
    differentialDiagnosis: ['cardiogenic-pulmonary-edema', 'diffuse-alveolar-hemorrhage', 'interstitial-pneumonia'],
    specialists: ['intensivist', 'pulmonologist'],
    prevalence: 'uncommon',
    crisis: true
  },

  'pleural-effusion': {
    id: 'pleural-effusion',
    name: 'Pleural Effusion',
    nameAr: 'الانصباب الجنبي',
    nameDe: 'Pleuraerguss',
    nameFr: 'Épanchement pleural',
    icd11: 'CB27',
    snomed: '60046008',
    category: 'respiratory',
    urgency: 'routine',
    primarySymptoms: ['shortness-breath', 'pleuritic-chest-pain', 'decreased-breath-sounds'],
    secondarySymptoms: ['cough', 'dullness-to-percussion', 'decreased-chest-expansion'],
    associatedSymptoms: ['fever-if-infected', 'weight-loss-if-malignant'],
    riskFactors: ['heart-failure', 'pneumonia', 'malignancy', 'pulmonary-embolism', 'liver-cirrhosis', 'renal-failure'],
    ageGroups: ['adult', 'elderly'],
    genderPrevalence: 'equal',
    description: 'Fluid accumulation between lung and chest wall with various causes.',
    immediateAction: 'Chest X-ray, diagnostic thoracentesis. Treat underlying cause.',
    redFlags: ['large effusion with respiratory distress', 'empyema', 'hemothorax'],
    differentialDiagnosis: ['pneumonia', 'lung-collapse', 'elevated-hemidiaphragm'],
    specialists: ['pulmonologist', 'thoracic-surgeon'],
    prevalence: 'common'
  }
};

// ============================================================================
// GASTROINTESTINAL CONDITIONS (150+)
// ============================================================================

export const GASTROINTESTINAL_CONDITIONS: Record<string, MedicalCondition> = {
  'gi-bleeding-upper': {
    id: 'gi-bleeding-upper',
    name: 'Upper GI Bleeding',
    nameAr: 'نزيف الجهاز الهضمي العلوي',
    nameDe: 'Obere Gastrointestinalblutung',
    nameFr: 'Hémorragie digestive haute',
    icd11: 'DA95.0',
    snomed: '74474003',
    category: 'gastrointestinal',
    urgency: 'emergency',
    primarySymptoms: ['hematemesis', 'melena', 'hypotension'],
    secondarySymptoms: ['tachycardia', 'dizziness', 'syncope'],
    associatedSymptoms: ['epigastric-pain', 'nausea', 'pallor'],
    riskFactors: ['peptic-ulcer', 'varices', 'nsaid-use', 'anticoagulation', 'alcoholism', 'h-pylori'],
    ageGroups: ['adult', 'elderly'],
    genderPrevalence: 'male',
    description: 'Bleeding from esophagus, stomach, or duodenum - potentially life-threatening.',
    immediateAction: 'Emergency IV access, blood transfusion, PPI. Urgent endoscopy within 24 hours.',
    redFlags: ['hemodynamic instability', 'ongoing transfusion requirement', 'variceal bleeding', 'bright red hematemesis'],
    differentialDiagnosis: ['peptic-ulcer-bleed', 'variceal-bleed', 'mallory-weiss-tear', 'gastric-cancer'],
    specialists: ['gastroenterologist', 'emergency-medicine'],
    prevalence: 'common',
    crisis: true
  },

  'gi-bleeding-lower': {
    id: 'gi-bleeding-lower',
    name: 'Lower GI Bleeding',
    nameAr: 'نزيف الجهاز الهضمي السفلي',
    nameDe: 'Untere Gastrointestinalblutung',
    nameFr: 'Hémorragie digestive basse',
    icd11: 'DA95.1',
    snomed: '281102002',
    category: 'gastrointestinal',
    urgency: 'urgent',
    primarySymptoms: ['hematochezia', 'rectal-bleeding', 'maroon-stool'],
    secondarySymptoms: ['abdominal-cramps', 'diarrhea', 'urgency'],
    associatedSymptoms: ['dizziness', 'fatigue', 'pallor'],
    riskFactors: ['diverticulosis', 'hemorrhoids', 'colorectal-cancer', 'angiodysplasia', 'ibd', 'anticoagulation'],
    ageGroups: ['adult', 'elderly'],
    genderPrevalence: 'equal',
    description: 'Bleeding from colon, rectum, or anus with various etiologies.',
    immediateAction: 'Stabilize hemodynamics. Colonoscopy when prepared. CT angiography if severe.',
    redFlags: ['hemodynamic instability', 'ongoing bleeding', 'age >50 with new bleeding'],
    differentialDiagnosis: ['hemorrhoids', 'diverticular-bleed', 'colorectal-cancer', 'ibd', 'angiodysplasia'],
    specialists: ['gastroenterologist', 'colorectal-surgeon'],
    prevalence: 'common'
  },

  'acute-liver-failure': {
    id: 'acute-liver-failure',
    name: 'Acute Liver Failure',
    nameAr: 'فشل الكبد الحاد',
    nameDe: 'Akutes Leberversagen',
    nameFr: 'Insuffisance hépatique aiguë',
    icd11: 'DB93.0',
    snomed: '197270009',
    category: 'gastrointestinal',
    urgency: 'emergency',
    primarySymptoms: ['jaundice', 'coagulopathy', 'encephalopathy'],
    secondarySymptoms: ['nausea', 'vomiting', 'abdominal-pain'],
    associatedSymptoms: ['asterixis', 'hypoglycemia', 'cerebral-edema'],
    riskFactors: ['acetaminophen-overdose', 'viral-hepatitis', 'drug-induced', 'autoimmune-hepatitis', 'wilsons-disease'],
    ageGroups: ['adult'],
    genderPrevalence: 'female',
    description: 'Rapid loss of liver function in previously healthy liver - often requires transplant.',
    immediateAction: 'ICU admission. N-acetylcysteine if acetaminophen. Evaluate for liver transplant.',
    redFlags: ['grade III/IV encephalopathy', 'INR >6.5', 'pH <7.3', 'creatinine >3.4'],
    differentialDiagnosis: ['acute-on-chronic-liver-failure', 'sepsis', 'drug-toxicity'],
    specialists: ['hepatologist', 'transplant-surgeon', 'intensivist'],
    prevalence: 'rare',
    crisis: true
  },

  'inflammatory-bowel-disease-flare': {
    id: 'inflammatory-bowel-disease-flare',
    name: 'IBD Flare (Crohn\'s/Ulcerative Colitis)',
    nameAr: 'نوبة مرض الأمعاء الالتهابي',
    nameDe: 'CED-Schub',
    nameFr: 'Poussée de MICI',
    icd11: 'DD70',
    snomed: '24526004',
    category: 'gastrointestinal',
    urgency: 'urgent',
    primarySymptoms: ['bloody-diarrhea', 'abdominal-pain-crampy', 'urgency'],
    secondarySymptoms: ['fever', 'weight-loss', 'fatigue'],
    associatedSymptoms: ['tenesmus', 'nocturnal-diarrhea', 'extraintestinal-manifestations'],
    riskFactors: ['known-ibd', 'nsaid-use', 'infection', 'stress', 'smoking-crohns'],
    ageGroups: ['adolescent', 'adult'],
    genderPrevalence: 'equal',
    description: 'Acute worsening of inflammatory bowel disease requiring treatment escalation.',
    immediateAction: 'Rule out infection. Steroids for moderate-severe. Biologic therapy may be needed.',
    redFlags: ['toxic megacolon', 'severe bleeding', 'signs of perforation', 'severe malnutrition'],
    differentialDiagnosis: ['infectious-colitis', 'c-diff', 'ischemic-colitis', 'colorectal-cancer'],
    specialists: ['gastroenterologist'],
    prevalence: 'common'
  },

  'acute-mesenteric-ischemia': {
    id: 'acute-mesenteric-ischemia',
    name: 'Acute Mesenteric Ischemia',
    nameAr: 'نقص تروية المساريق الحاد',
    nameDe: 'Akute Mesenterialischämie',
    nameFr: 'Ischémie mésentérique aiguë',
    icd11: 'DA90',
    snomed: '35999006',
    category: 'gastrointestinal',
    urgency: 'emergency',
    primarySymptoms: ['abdominal-pain-severe-out-of-proportion', 'nausea', 'vomiting'],
    secondarySymptoms: ['bloody-diarrhea', 'abdominal-distension', 'tachycardia'],
    associatedSymptoms: ['fever', 'altered-mental-status', 'shock'],
    riskFactors: ['atrial-fibrillation', 'heart-failure', 'atherosclerosis', 'hypercoagulable-state', 'recent-mi'],
    ageGroups: ['elderly'],
    genderPrevalence: 'equal',
    description: 'Sudden loss of blood supply to intestines - surgical emergency with high mortality.',
    immediateAction: 'EMERGENCY CT angiography. Anticoagulation. Emergency surgery or endovascular intervention.',
    redFlags: ['pain out of proportion to exam', 'peritonitis', 'metabolic acidosis', 'elevated lactate'],
    differentialDiagnosis: ['bowel-obstruction', 'acute-pancreatitis', 'perforated-viscus', 'aortic-dissection'],
    specialists: ['vascular-surgeon', 'general-surgeon', 'gastroenterologist'],
    prevalence: 'rare',
    crisis: true
  },

  'hepatic-encephalopathy': {
    id: 'hepatic-encephalopathy',
    name: 'Hepatic Encephalopathy',
    nameAr: 'اعتلال الدماغ الكبدي',
    nameDe: 'Hepatische Enzephalopathie',
    nameFr: 'Encéphalopathie hépatique',
    icd11: 'DB93.1',
    snomed: '13920009',
    category: 'gastrointestinal',
    urgency: 'urgent',
    primarySymptoms: ['confusion', 'asterixis', 'altered-sleep-pattern'],
    secondarySymptoms: ['lethargy', 'disorientation', 'personality-changes'],
    associatedSymptoms: ['fetor-hepaticus', 'hyperreflexia', 'constructional-apraxia'],
    riskFactors: ['liver-cirrhosis', 'gi-bleeding', 'infection', 'constipation', 'dehydration', 'electrolyte-imbalance'],
    ageGroups: ['adult', 'elderly'],
    genderPrevalence: 'equal',
    description: 'Brain dysfunction due to liver failure and accumulation of toxins.',
    immediateAction: 'Identify and treat precipitant. Lactulose. Rifaximin. Rule out other causes of confusion.',
    redFlags: ['grade III-IV encephalopathy', 'cerebral edema', 'respiratory failure'],
    differentialDiagnosis: ['alcohol-withdrawal', 'sepsis', 'hypoglycemia', 'drug-intoxication', 'stroke'],
    specialists: ['hepatologist', 'gastroenterologist'],
    prevalence: 'common'
  }
};

// ============================================================================
// NEUROLOGICAL CONDITIONS (120+)
// ============================================================================

export const NEUROLOGICAL_CONDITIONS: Record<string, MedicalCondition> = {
  'status-epilepticus': {
    id: 'status-epilepticus',
    name: 'Status Epilepticus',
    nameAr: 'الحالة الصرعية',
    nameDe: 'Status epilepticus',
    nameFr: 'État de mal épileptique',
    icd11: '8A62',
    snomed: '230456004',
    category: 'neurological',
    urgency: 'emergency',
    primarySymptoms: ['seizure-prolonged', 'seizure-recurrent', 'altered-consciousness'],
    secondarySymptoms: ['cyanosis', 'hyperthermia', 'incontinence'],
    associatedSymptoms: ['tachycardia', 'hypertension', 'metabolic-acidosis'],
    riskFactors: ['known-epilepsy', 'medication-noncompliance', 'alcohol-withdrawal', 'infection', 'stroke', 'tumor'],
    ageGroups: ['infant', 'child', 'adult', 'elderly'],
    genderPrevalence: 'equal',
    description: 'Continuous seizure activity >5 minutes or recurrent seizures without recovery - neurological emergency.',
    immediateAction: 'EMERGENCY. Secure airway. IV benzodiazepines immediately. Second-line anticonvulsants if refractory.',
    redFlags: ['seizure >5 minutes', 'multiple seizures without recovery', 'refractory to first-line treatment'],
    differentialDiagnosis: ['psychogenic-seizure', 'syncope', 'movement-disorder', 'encephalopathy'],
    specialists: ['neurologist', 'emergency-medicine', 'intensivist'],
    prevalence: 'uncommon',
    crisis: true
  },

  'bacterial-meningitis': {
    id: 'bacterial-meningitis',
    name: 'Bacterial Meningitis',
    nameAr: 'التهاب السحايا البكتيري',
    nameDe: 'Bakterielle Meningitis',
    nameFr: 'Méningite bactérienne',
    icd11: '1C11',
    snomed: '95883001',
    category: 'neurological',
    urgency: 'emergency',
    primarySymptoms: ['headache-severe', 'fever', 'neck-stiffness'],
    secondarySymptoms: ['photophobia', 'altered-mental-status', 'nausea-vomiting'],
    associatedSymptoms: ['kernig-sign', 'brudzinski-sign', 'petechial-rash', 'seizures'],
    riskFactors: ['immunosuppression', 'close-contacts', 'csf-leak', 'recent-neurosurgery', 'splenectomy'],
    ageGroups: ['infant', 'child', 'adolescent', 'adult', 'elderly'],
    genderPrevalence: 'equal',
    description: 'Life-threatening bacterial infection of the meninges requiring immediate antibiotics.',
    immediateAction: 'EMERGENCY. IV antibiotics within 1 hour. Do not delay for LP if suspected. Dexamethasone before antibiotics.',
    redFlags: ['rapid deterioration', 'petechial rash', 'shock', 'seizures', 'focal neurological signs'],
    differentialDiagnosis: ['viral-meningitis', 'subarachnoid-hemorrhage', 'encephalitis', 'brain-abscess'],
    specialists: ['neurologist', 'infectious-disease', 'emergency-medicine'],
    prevalence: 'uncommon',
    crisis: true
  },

  'subarachnoid-hemorrhage': {
    id: 'subarachnoid-hemorrhage',
    name: 'Subarachnoid Hemorrhage',
    nameAr: 'نزيف تحت العنكبوتية',
    nameDe: 'Subarachnoidalblutung',
    nameFr: 'Hémorragie sous-arachnoïdienne',
    icd11: '8B01',
    snomed: '21454007',
    category: 'neurological',
    urgency: 'emergency',
    primarySymptoms: ['headache-thunderclap', 'headache-worst-of-life', 'neck-stiffness'],
    secondarySymptoms: ['photophobia', 'nausea-vomiting', 'altered-consciousness'],
    associatedSymptoms: ['focal-neurological-deficit', 'seizure', 'syncope'],
    riskFactors: ['hypertension', 'smoking', 'family-history-aneurysm', 'polycystic-kidney-disease', 'connective-tissue-disorder'],
    ageGroups: ['adult'],
    genderPrevalence: 'female',
    description: 'Bleeding into subarachnoid space, usually from ruptured aneurysm - high mortality.',
    immediateAction: 'EMERGENCY CT head immediately. If negative and high suspicion, LP. Neurosurgery/endovascular intervention.',
    redFlags: ['thunderclap headache', 'altered consciousness', 'focal neurological signs', 'rebleeding'],
    differentialDiagnosis: ['migraine', 'meningitis', 'intracerebral-hemorrhage', 'hypertensive-crisis'],
    specialists: ['neurosurgeon', 'interventional-neuroradiology', 'neurointensivist'],
    prevalence: 'uncommon',
    crisis: true
  },

  'guillain-barre-syndrome': {
    id: 'guillain-barre-syndrome',
    name: 'Guillain-Barré Syndrome',
    nameAr: 'متلازمة غيلان باريه',
    nameDe: 'Guillain-Barré-Syndrom',
    nameFr: 'Syndrome de Guillain-Barré',
    icd11: '8C00.0',
    snomed: '40956001',
    category: 'neurological',
    urgency: 'urgent',
    primarySymptoms: ['weakness-ascending', 'numbness-tingling', 'areflexia'],
    secondarySymptoms: ['back-pain', 'facial-weakness', 'difficulty-swallowing'],
    associatedSymptoms: ['autonomic-dysfunction', 'respiratory-weakness', 'ophthalmoplegia'],
    riskFactors: ['recent-infection', 'campylobacter', 'flu-vaccination', 'surgery'],
    ageGroups: ['adult', 'elderly'],
    genderPrevalence: 'male',
    description: 'Autoimmune attack on peripheral nerves causing ascending paralysis - may affect breathing.',
    immediateAction: 'Hospital admission. Monitor respiratory function. IVIG or plasmapheresis.',
    redFlags: ['respiratory compromise (FVC <20ml/kg)', 'rapid progression', 'bulbar involvement', 'autonomic instability'],
    differentialDiagnosis: ['spinal-cord-compression', 'transverse-myelitis', 'myasthenia-gravis', 'botulism'],
    specialists: ['neurologist', 'intensivist'],
    prevalence: 'rare',
    crisis: true
  },

  'myasthenic-crisis': {
    id: 'myasthenic-crisis',
    name: 'Myasthenic Crisis',
    nameAr: 'أزمة الوهن العضلي',
    nameDe: 'Myasthene Krise',
    nameFr: 'Crise myasthénique',
    icd11: '8C60.0',
    snomed: '91637004',
    category: 'neurological',
    urgency: 'emergency',
    primarySymptoms: ['respiratory-failure', 'severe-weakness', 'dysphagia'],
    secondarySymptoms: ['dysarthria', 'ptosis', 'diplopia'],
    associatedSymptoms: ['anxiety', 'tachycardia', 'diaphoresis'],
    riskFactors: ['known-myasthenia-gravis', 'infection', 'surgery', 'medication-changes', 'pregnancy'],
    ageGroups: ['adult', 'elderly'],
    genderPrevalence: 'female',
    description: 'Life-threatening respiratory failure in myasthenia gravis requiring ICU care.',
    immediateAction: 'ICU admission. Intubation if needed. IVIG or plasmapheresis. Avoid certain medications.',
    redFlags: ['FVC <15ml/kg', 'inability to count to 20 in one breath', 'paradoxical breathing', 'hypercapnia'],
    differentialDiagnosis: ['cholinergic-crisis', 'guillain-barre', 'botulism', 'als'],
    specialists: ['neurologist', 'intensivist'],
    prevalence: 'rare',
    crisis: true
  },

  'acute-spinal-cord-compression': {
    id: 'acute-spinal-cord-compression',
    name: 'Acute Spinal Cord Compression',
    nameAr: 'ضغط الحبل الشوكي الحاد',
    nameDe: 'Akute Rückenmarkskompression',
    nameFr: 'Compression médullaire aiguë',
    icd11: '8B44',
    snomed: '48522003',
    category: 'neurological',
    urgency: 'emergency',
    primarySymptoms: ['back-pain-severe', 'leg-weakness', 'sensory-level'],
    secondarySymptoms: ['urinary-retention', 'fecal-incontinence', 'gait-disturbance'],
    associatedSymptoms: ['hyperreflexia', 'clonus', 'babinski-positive'],
    riskFactors: ['malignancy', 'trauma', 'disc-herniation', 'epidural-abscess', 'hematoma'],
    ageGroups: ['adult', 'elderly'],
    genderPrevalence: 'equal',
    description: 'Compression of spinal cord requiring emergency decompression to prevent permanent paralysis.',
    immediateAction: 'EMERGENCY MRI spine. High-dose steroids if malignant. Urgent surgical decompression.',
    redFlags: ['rapid progression', 'bladder/bowel dysfunction', 'saddle anesthesia', 'bilateral weakness'],
    differentialDiagnosis: ['cauda-equina-syndrome', 'transverse-myelitis', 'guillain-barre', 'stroke'],
    specialists: ['neurosurgeon', 'spine-surgeon', 'oncologist'],
    prevalence: 'uncommon',
    crisis: true
  }
};

// ============================================================================
// COMBINE ALL CONDITIONS
// ============================================================================

export const EXTENDED_CONDITIONS_DATABASE_V2: Record<string, MedicalCondition> = {
  ...SURGICAL_CONDITIONS,
  ...CARDIOVASCULAR_CONDITIONS,
  ...RESPIRATORY_CONDITIONS,
  ...GASTROINTESTINAL_CONDITIONS,
  ...NEUROLOGICAL_CONDITIONS
};

// Calculate total conditions
export const TOTAL_CONDITIONS_COUNT = Object.keys(EXTENDED_CONDITIONS_DATABASE_V2).length;

console.log(\`🏥 MediSense AI Pro™ Extended Database V2 loaded: \${TOTAL_CONDITIONS_COUNT} conditions\`);
