/**
 * MediSense AI Pro™ - Extended Conditions Database
 * Additional Medical Conditions for Comprehensive Coverage
 * 
 * This extends the base conditions database with:
 * - More specialty-specific conditions
 * - Pediatric conditions
 * - Infectious diseases
 * - Skin conditions
 * - Women's health conditions
 * - Men's health conditions
 * - Autoimmune conditions
 */

import { MedicalCondition } from './conditions-database'

// ============================================================================
// EXTENDED CONDITIONS DATABASE
// ============================================================================

export const EXTENDED_CONDITIONS: Record<string, MedicalCondition> = {
  // ============================================================================
  // CARDIOVASCULAR (Extended)
  // ============================================================================
  
  'angina': {
    id: 'angina',
    name: 'Angina Pectoris',
    nameAr: 'الذبحة الصدرية',
    nameDe: 'Angina Pectoris',
    nameFr: 'Angine de poitrine',
    icd11: 'BA80',
    snomed: '194828000',
    category: 'cardiovascular',
    urgency: 'urgent',
    primarySymptoms: ['chest-pain', 'chest-pain-pressure', 'chest-tightness'],
    secondarySymptoms: ['shortness-breath-exertion', 'fatigue', 'dizziness'],
    associatedSymptoms: ['nausea', 'sweating', 'arm-pain-left'],
    riskFactors: ['hypertension', 'diabetes', 'smoking', 'high-cholesterol', 'obesity', 'family-history-heart', 'age>55'],
    ageGroups: ['adult', 'elderly'],
    genderPrevalence: 'male',
    description: 'Angina is chest pain or discomfort caused by reduced blood flow to the heart muscle, typically triggered by physical exertion or stress.',
    specialists: ['cardiologist'],
    prevalence: 'common',
    differentialDiagnosis: ['heart-attack', 'gerd', 'musculoskeletal-pain', 'anxiety']
  },
  
  'heart-failure': {
    id: 'heart-failure',
    name: 'Heart Failure (Congestive)',
    nameAr: 'قصور القلب',
    nameDe: 'Herzinsuffizienz',
    nameFr: 'Insuffisance cardiaque',
    icd11: 'BD10',
    snomed: '84114007',
    category: 'cardiovascular',
    urgency: 'urgent',
    primarySymptoms: ['shortness-breath', 'shortness-breath-exertion', 'fatigue', 'leg-swelling'],
    secondarySymptoms: ['rapid-heartbeat', 'cough', 'weight-gain-unexplained'],
    associatedSymptoms: ['loss-appetite', 'nausea', 'confusion', 'frequent-urination'],
    riskFactors: ['hypertension', 'heart-attack-history', 'diabetes', 'obesity', 'age>65'],
    ageGroups: ['adult', 'elderly'],
    genderPrevalence: 'equal',
    description: 'Heart failure occurs when the heart cannot pump blood efficiently enough to meet the body\'s needs.',
    specialists: ['cardiologist'],
    prevalence: 'common',
    typicalDuration: 'chronic'
  },
  
  'pericarditis': {
    id: 'pericarditis',
    name: 'Pericarditis',
    nameAr: 'التهاب التامور',
    nameDe: 'Perikarditis',
    nameFr: 'Péricardite',
    icd11: 'BB40',
    snomed: '3238004',
    category: 'cardiovascular',
    urgency: 'urgent',
    primarySymptoms: ['chest-pain-sharp', 'chest-pain-breathing'],
    secondarySymptoms: ['fever', 'shortness-breath', 'palpitations'],
    associatedSymptoms: ['fatigue', 'cough-dry', 'weakness'],
    riskFactors: ['viral-infection', 'autoimmune-disease', 'recent-heart-surgery', 'kidney-failure'],
    ageGroups: ['adult', 'elderly'],
    genderPrevalence: 'male',
    description: 'Pericarditis is inflammation of the pericardium, the sac-like covering around the heart.',
    specialists: ['cardiologist'],
    prevalence: 'uncommon',
    differentialDiagnosis: ['heart-attack', 'pulmonary-embolism', 'pneumonia']
  },

  // ============================================================================
  // RESPIRATORY (Extended)
  // ============================================================================
  
  'bronchitis-acute': {
    id: 'bronchitis-acute',
    name: 'Acute Bronchitis',
    nameAr: 'التهاب الشعب الهوائية الحاد',
    nameDe: 'Akute Bronchitis',
    nameFr: 'Bronchite aiguë',
    icd11: 'CA20',
    snomed: '10509002',
    category: 'respiratory',
    urgency: 'routine',
    primarySymptoms: ['cough', 'cough-productive', 'chest-tightness'],
    secondarySymptoms: ['low-grade-fever', 'fatigue', 'shortness-breath'],
    associatedSymptoms: ['sore-throat', 'body-aches', 'headache'],
    riskFactors: ['smoking', 'recent-cold', 'pollution-exposure', 'weakened-immunity'],
    ageGroups: ['child', 'adolescent', 'adult', 'elderly'],
    genderPrevalence: 'equal',
    description: 'Acute bronchitis is inflammation of the bronchial tubes, usually caused by viral infection.',
    specialists: ['pulmonologist', 'general-practitioner'],
    prevalence: 'common',
    typicalDuration: '1-3 weeks'
  },
  
  'sinusitis': {
    id: 'sinusitis',
    name: 'Sinusitis',
    nameAr: 'التهاب الجيوب الأنفية',
    nameDe: 'Sinusitis',
    nameFr: 'Sinusite',
    icd11: 'CA01',
    snomed: '36971009',
    category: 'respiratory',
    urgency: 'routine',
    primarySymptoms: ['sinus-pressure', 'stuffy-nose', 'facial-pain'],
    secondarySymptoms: ['headache', 'post-nasal-drip', 'cough'],
    associatedSymptoms: ['fever', 'fatigue', 'loss-of-smell', 'ear-pain'],
    riskFactors: ['allergies', 'recent-cold', 'nasal-polyps', 'deviated-septum'],
    ageGroups: ['child', 'adolescent', 'adult', 'elderly'],
    genderPrevalence: 'equal',
    description: 'Sinusitis is inflammation or swelling of the tissue lining the sinuses.',
    specialists: ['ent', 'general-practitioner'],
    prevalence: 'common',
    typicalDuration: '7-10 days (acute), chronic if >12 weeks'
  },
  
  'asthma-attack': {
    id: 'asthma-attack',
    name: 'Asthma Attack (Acute Exacerbation)',
    nameAr: 'نوبة ربو',
    nameDe: 'Asthmaanfall',
    nameFr: 'Crise d\'asthme',
    icd11: 'CA23.1',
    snomed: '266364000',
    category: 'respiratory',
    urgency: 'emergency',
    primarySymptoms: ['wheezing', 'shortness-breath', 'difficulty-breathing', 'chest-tightness'],
    secondarySymptoms: ['cough', 'rapid-breathing', 'anxiety'],
    associatedSymptoms: ['blue-lips-fingers', 'inability-to-speak', 'sweating'],
    riskFactors: ['asthma', 'allergen-exposure', 'respiratory-infection', 'exercise', 'cold-air'],
    ageGroups: ['child', 'adolescent', 'adult', 'elderly'],
    genderPrevalence: 'equal',
    description: 'An asthma attack is a sudden worsening of asthma symptoms caused by the tightening of muscles around the airways.',
    immediateAction: 'Use rescue inhaler immediately. Seek emergency care if no improvement in 15-20 minutes.',
    specialists: ['pulmonologist', 'allergist', 'emergency-medicine'],
    prevalence: 'common',
    crisis: true
  },
  
  'pleurisy': {
    id: 'pleurisy',
    name: 'Pleurisy',
    nameAr: 'التهاب الجنبة',
    nameDe: 'Pleuritis',
    nameFr: 'Pleurésie',
    icd11: 'CB23',
    snomed: '4195003',
    category: 'respiratory',
    urgency: 'urgent',
    primarySymptoms: ['chest-pain-sharp', 'chest-pain-breathing'],
    secondarySymptoms: ['shortness-breath', 'cough-dry'],
    associatedSymptoms: ['fever', 'shoulder-pain'],
    riskFactors: ['viral-infection', 'pneumonia', 'pulmonary-embolism', 'autoimmune-disease'],
    ageGroups: ['adult', 'elderly'],
    genderPrevalence: 'equal',
    description: 'Pleurisy is inflammation of the lining around the lungs, causing sharp chest pain that worsens with breathing.',
    specialists: ['pulmonologist'],
    prevalence: 'uncommon'
  },

  // ============================================================================
  // GASTROINTESTINAL (Extended)
  // ============================================================================
  
  'peptic-ulcer': {
    id: 'peptic-ulcer',
    name: 'Peptic Ulcer Disease',
    nameAr: 'قرحة المعدة',
    nameDe: 'Magengeschwür',
    nameFr: 'Ulcère peptique',
    icd11: 'DA40',
    snomed: '13200003',
    category: 'gastrointestinal',
    urgency: 'routine',
    primarySymptoms: ['abdominal-pain', 'heartburn', 'nausea'],
    secondarySymptoms: ['bloating', 'loss-appetite', 'vomiting'],
    associatedSymptoms: ['weight-loss-unexplained', 'blood-stool', 'fatigue'],
    riskFactors: ['h-pylori-infection', 'nsaid-use', 'smoking', 'alcohol', 'stress'],
    ageGroups: ['adult', 'elderly'],
    genderPrevalence: 'male',
    description: 'Peptic ulcers are sores that develop on the lining of the stomach or upper small intestine.',
    specialists: ['gastroenterologist'],
    prevalence: 'common',
    differentialDiagnosis: ['gerd', 'gastritis', 'gallstones']
  },
  
  'gallstones': {
    id: 'gallstones',
    name: 'Gallstones (Cholelithiasis)',
    nameAr: 'حصوات المرارة',
    nameDe: 'Gallensteine',
    nameFr: 'Calculs biliaires',
    icd11: 'DC10',
    snomed: '235919008',
    category: 'gastrointestinal',
    urgency: 'urgent',
    primarySymptoms: ['abdominal-pain-right-upper', 'abdominal-pain-severe'],
    secondarySymptoms: ['nausea', 'vomiting', 'back-pain'],
    associatedSymptoms: ['jaundice', 'fever', 'bloating'],
    riskFactors: ['female', 'obesity', 'age>40', 'rapid-weight-loss', 'pregnancy', 'family-history'],
    ageGroups: ['adult', 'elderly'],
    genderPrevalence: 'female',
    description: 'Gallstones are hardened deposits in the gallbladder that can block bile ducts and cause severe pain.',
    specialists: ['gastroenterologist', 'general-surgeon'],
    prevalence: 'common'
  },
  
  'diverticulitis': {
    id: 'diverticulitis',
    name: 'Diverticulitis',
    nameAr: 'التهاب الرتج',
    nameDe: 'Divertikulitis',
    nameFr: 'Diverticulite',
    icd11: 'DD20',
    snomed: '197270001',
    category: 'gastrointestinal',
    urgency: 'urgent',
    primarySymptoms: ['abdominal-pain-left-lower', 'fever'],
    secondarySymptoms: ['nausea', 'constipation', 'diarrhea', 'bloating'],
    associatedSymptoms: ['blood-stool', 'vomiting', 'frequent-urination'],
    riskFactors: ['age>50', 'low-fiber-diet', 'obesity', 'sedentary-lifestyle', 'smoking'],
    ageGroups: ['adult', 'elderly'],
    genderPrevalence: 'equal',
    description: 'Diverticulitis occurs when small pouches in the digestive tract become inflamed or infected.',
    specialists: ['gastroenterologist', 'general-surgeon'],
    prevalence: 'common'
  },
  
  'celiac-disease': {
    id: 'celiac-disease',
    name: 'Celiac Disease',
    nameAr: 'مرض السيلياك',
    nameDe: 'Zöliakie',
    nameFr: 'Maladie cœliaque',
    icd11: 'DA95.0',
    snomed: '396331005',
    category: 'gastrointestinal',
    urgency: 'routine',
    primarySymptoms: ['diarrhea', 'bloating', 'abdominal-pain'],
    secondarySymptoms: ['fatigue', 'weight-loss-unexplained', 'nausea'],
    associatedSymptoms: ['anemia', 'joint-pain', 'skin-rash', 'depression'],
    riskFactors: ['family-history', 'type-1-diabetes', 'autoimmune-disease', 'down-syndrome'],
    ageGroups: ['child', 'adolescent', 'adult'],
    genderPrevalence: 'female',
    description: 'Celiac disease is an immune reaction to eating gluten that damages the small intestine.',
    specialists: ['gastroenterologist'],
    prevalence: 'uncommon',
    typicalDuration: 'chronic'
  },
  
  'crohns-disease': {
    id: 'crohns-disease',
    name: 'Crohn\'s Disease',
    nameAr: 'مرض كرون',
    nameDe: 'Morbus Crohn',
    nameFr: 'Maladie de Crohn',
    icd11: 'DD70',
    snomed: '34000006',
    category: 'gastrointestinal',
    urgency: 'routine',
    primarySymptoms: ['diarrhea', 'abdominal-pain', 'fatigue'],
    secondarySymptoms: ['blood-stool', 'weight-loss-unexplained', 'fever'],
    associatedSymptoms: ['joint-pain', 'eye-pain', 'skin-lesions', 'mouth-ulcers'],
    riskFactors: ['family-history', 'smoking', 'nsaid-use', 'age-15-35'],
    ageGroups: ['adolescent', 'adult'],
    genderPrevalence: 'equal',
    description: 'Crohn\'s disease is an inflammatory bowel disease that causes chronic inflammation of the digestive tract.',
    specialists: ['gastroenterologist'],
    prevalence: 'uncommon',
    typicalDuration: 'chronic'
  },
  
  'ulcerative-colitis': {
    id: 'ulcerative-colitis',
    name: 'Ulcerative Colitis',
    nameAr: 'التهاب القولون التقرحي',
    nameDe: 'Colitis ulcerosa',
    nameFr: 'Colite ulcéreuse',
    icd11: 'DD71',
    snomed: '64766004',
    category: 'gastrointestinal',
    urgency: 'routine',
    primarySymptoms: ['diarrhea-bloody', 'abdominal-pain', 'urgency-defecation'],
    secondarySymptoms: ['fatigue', 'weight-loss-unexplained', 'fever'],
    associatedSymptoms: ['joint-pain', 'skin-lesions', 'eye-inflammation'],
    riskFactors: ['family-history', 'age-15-30', 'caucasian', 'ashkenazi-jewish'],
    ageGroups: ['adolescent', 'adult'],
    genderPrevalence: 'equal',
    description: 'Ulcerative colitis is an inflammatory bowel disease that causes inflammation and ulcers in the colon.',
    specialists: ['gastroenterologist'],
    prevalence: 'uncommon',
    typicalDuration: 'chronic'
  },

  // ============================================================================
  // NEUROLOGICAL (Extended)
  // ============================================================================
  
  'epilepsy': {
    id: 'epilepsy',
    name: 'Epilepsy',
    nameAr: 'الصرع',
    nameDe: 'Epilepsie',
    nameFr: 'Épilepsie',
    icd11: '8A60',
    snomed: '84757009',
    category: 'neurological',
    urgency: 'routine',
    primarySymptoms: ['seizure', 'confusion', 'loss-of-consciousness'],
    secondarySymptoms: ['muscle-jerking', 'staring-spells', 'anxiety'],
    associatedSymptoms: ['fatigue', 'headache', 'memory-problems'],
    riskFactors: ['head-injury', 'family-history', 'stroke', 'brain-infection', 'dementia'],
    ageGroups: ['infant', 'child', 'adolescent', 'adult', 'elderly'],
    genderPrevalence: 'equal',
    description: 'Epilepsy is a neurological disorder characterized by recurrent, unprovoked seizures.',
    specialists: ['neurologist', 'epileptologist'],
    prevalence: 'common',
    typicalDuration: 'chronic'
  },
  
  'parkinsons': {
    id: 'parkinsons',
    name: 'Parkinson\'s Disease',
    nameAr: 'مرض باركنسون',
    nameDe: 'Parkinson-Krankheit',
    nameFr: 'Maladie de Parkinson',
    icd11: '8A00.0',
    snomed: '49049000',
    category: 'neurological',
    urgency: 'routine',
    primarySymptoms: ['tremor', 'muscle-stiffness', 'slow-movement', 'balance-problems'],
    secondarySymptoms: ['speech-changes', 'writing-changes', 'mask-like-face'],
    associatedSymptoms: ['depression', 'sleep-problems', 'constipation', 'loss-of-smell'],
    riskFactors: ['age>60', 'male', 'family-history', 'pesticide-exposure', 'head-injury'],
    ageGroups: ['adult', 'elderly'],
    genderPrevalence: 'male',
    description: 'Parkinson\'s disease is a progressive nervous system disorder that affects movement.',
    specialists: ['neurologist', 'movement-disorder-specialist'],
    prevalence: 'uncommon',
    typicalDuration: 'chronic'
  },
  
  'multiple-sclerosis': {
    id: 'multiple-sclerosis',
    name: 'Multiple Sclerosis',
    nameAr: 'التصلب المتعدد',
    nameDe: 'Multiple Sklerose',
    nameFr: 'Sclérose en plaques',
    icd11: '8A40',
    snomed: '24700007',
    category: 'neurological',
    urgency: 'routine',
    primarySymptoms: ['numbness-limbs', 'weakness', 'vision-changes', 'tingling'],
    secondarySymptoms: ['fatigue', 'balance-problems', 'dizziness'],
    associatedSymptoms: ['slurred-speech', 'bowel-problems', 'bladder-problems', 'cognitive-changes'],
    riskFactors: ['female', 'age-20-40', 'family-history', 'vitamin-d-deficiency', 'northern-climate'],
    ageGroups: ['adult'],
    genderPrevalence: 'female',
    description: 'Multiple sclerosis is a disease where the immune system attacks the protective covering of nerves.',
    specialists: ['neurologist'],
    prevalence: 'uncommon',
    typicalDuration: 'chronic'
  },
  
  'bells-palsy': {
    id: 'bells-palsy',
    name: 'Bell\'s Palsy',
    nameAr: 'شلل بيل',
    nameDe: 'Bell-Lähmung',
    nameFr: 'Paralysie de Bell',
    icd11: '8B89.0',
    snomed: '193093009',
    category: 'neurological',
    urgency: 'urgent',
    primarySymptoms: ['numbness-face', 'facial-weakness', 'facial-drooping'],
    secondarySymptoms: ['drooling', 'eye-dryness', 'taste-changes'],
    associatedSymptoms: ['ear-pain', 'headache', 'sound-sensitivity'],
    riskFactors: ['viral-infection', 'pregnancy', 'diabetes', 'upper-respiratory-infection'],
    ageGroups: ['adult'],
    genderPrevalence: 'equal',
    description: 'Bell\'s palsy causes sudden weakness in facial muscles, usually on one side.',
    specialists: ['neurologist', 'ent'],
    prevalence: 'uncommon',
    typicalDuration: '2 weeks to 6 months',
    differentialDiagnosis: ['stroke', 'brain-tumor', 'lyme-disease']
  },
  
  'vertigo': {
    id: 'vertigo',
    name: 'Vertigo (BPPV)',
    nameAr: 'الدوار',
    nameDe: 'Schwindel',
    nameFr: 'Vertige',
    icd11: 'AB31.0',
    snomed: '399153001',
    category: 'neurological',
    urgency: 'routine',
    primarySymptoms: ['dizziness', 'spinning-sensation', 'balance-problems'],
    secondarySymptoms: ['nausea', 'vomiting', 'nystagmus'],
    associatedSymptoms: ['headache', 'tinnitus', 'hearing-loss'],
    riskFactors: ['age>50', 'head-injury', 'ear-infection', 'prolonged-bed-rest'],
    ageGroups: ['adult', 'elderly'],
    genderPrevalence: 'female',
    description: 'Benign paroxysmal positional vertigo (BPPV) causes brief episodes of mild to intense dizziness.',
    specialists: ['ent', 'neurologist'],
    prevalence: 'common'
  },

  // ============================================================================
  // INFECTIOUS DISEASES (Extended)
  // ============================================================================
  
  'strep-throat': {
    id: 'strep-throat',
    name: 'Strep Throat',
    nameAr: 'التهاب الحلق العقدي',
    nameDe: 'Streptokokken-Angina',
    nameFr: 'Angine streptococcique',
    icd11: 'CA02.0',
    snomed: '43878008',
    category: 'infectious',
    urgency: 'routine',
    primarySymptoms: ['sore-throat', 'fever', 'swollen-tonsils'],
    secondarySymptoms: ['headache', 'swollen-lymph-nodes', 'white-patches-throat'],
    associatedSymptoms: ['body-aches', 'nausea', 'loss-appetite'],
    riskFactors: ['age-5-15', 'close-contact-with-infected', 'winter-season'],
    ageGroups: ['child', 'adolescent', 'adult'],
    genderPrevalence: 'equal',
    description: 'Strep throat is a bacterial infection that causes inflammation and pain in the throat.',
    specialists: ['general-practitioner', 'ent'],
    prevalence: 'common',
    typicalDuration: '7-10 days with treatment'
  },
  
  'mononucleosis': {
    id: 'mononucleosis',
    name: 'Mononucleosis (Mono)',
    nameAr: 'داء كثرة الوحيدات العدائية',
    nameDe: 'Pfeiffersches Drüsenfieber',
    nameFr: 'Mononucléose',
    icd11: '1D80',
    snomed: '271558008',
    category: 'infectious',
    urgency: 'routine',
    primarySymptoms: ['fatigue', 'sore-throat', 'fever', 'swollen-lymph-nodes'],
    secondarySymptoms: ['headache', 'muscle-pain', 'loss-appetite'],
    associatedSymptoms: ['rash', 'swollen-spleen', 'jaundice'],
    riskFactors: ['age-15-24', 'close-contact-sharing-drinks', 'weakened-immunity'],
    ageGroups: ['adolescent', 'adult'],
    genderPrevalence: 'equal',
    description: 'Mononucleosis is a viral infection causing extreme fatigue, fever, and swollen lymph nodes.',
    specialists: ['general-practitioner', 'infectious-disease'],
    prevalence: 'common',
    typicalDuration: '2-4 weeks (fatigue may last months)'
  },
  
  'lyme-disease': {
    id: 'lyme-disease',
    name: 'Lyme Disease',
    nameAr: 'مرض لايم',
    nameDe: 'Borreliose',
    nameFr: 'Maladie de Lyme',
    icd11: '1C1G',
    snomed: '23502006',
    category: 'infectious',
    urgency: 'urgent',
    primarySymptoms: ['rash-bulls-eye', 'fever', 'fatigue', 'muscle-pain'],
    secondarySymptoms: ['headache', 'joint-pain', 'swollen-lymph-nodes'],
    associatedSymptoms: ['neck-stiffness', 'facial-palsy', 'irregular-heartbeat', 'numbness'],
    riskFactors: ['tick-bite', 'outdoor-activities', 'wooded-areas', 'spring-summer'],
    ageGroups: ['child', 'adolescent', 'adult', 'elderly'],
    genderPrevalence: 'equal',
    description: 'Lyme disease is a tick-borne illness that can cause a range of symptoms from rash to neurological problems.',
    specialists: ['infectious-disease', 'rheumatologist'],
    prevalence: 'uncommon'
  },
  
  'shingles': {
    id: 'shingles',
    name: 'Shingles (Herpes Zoster)',
    nameAr: 'الحزام الناري',
    nameDe: 'Gürtelrose',
    nameFr: 'Zona',
    icd11: '1E91',
    snomed: '4740000',
    category: 'infectious',
    urgency: 'urgent',
    primarySymptoms: ['rash-blistering', 'pain-burning', 'itching'],
    secondarySymptoms: ['fever', 'headache', 'fatigue'],
    associatedSymptoms: ['light-sensitivity', 'chills', 'upset-stomach'],
    riskFactors: ['age>50', 'weakened-immunity', 'history-chickenpox', 'stress'],
    ageGroups: ['adult', 'elderly'],
    genderPrevalence: 'equal',
    description: 'Shingles is a viral infection causing a painful rash, caused by the same virus as chickenpox.',
    specialists: ['dermatologist', 'infectious-disease'],
    prevalence: 'common'
  },
  
  'covid-19': {
    id: 'covid-19',
    name: 'COVID-19',
    nameAr: 'كوفيد-19',
    nameDe: 'COVID-19',
    nameFr: 'COVID-19',
    icd11: 'RA01',
    snomed: '840539006',
    category: 'infectious',
    urgency: 'urgent',
    primarySymptoms: ['fever', 'cough-dry', 'fatigue', 'loss-of-smell', 'loss-of-taste'],
    secondarySymptoms: ['shortness-breath', 'muscle-pain', 'sore-throat', 'headache'],
    associatedSymptoms: ['diarrhea', 'rash', 'confusion', 'chest-pain'],
    riskFactors: ['age>65', 'obesity', 'diabetes', 'heart-disease', 'immunocompromised'],
    ageGroups: ['infant', 'child', 'adolescent', 'adult', 'elderly'],
    genderPrevalence: 'equal',
    description: 'COVID-19 is a respiratory illness caused by the SARS-CoV-2 virus.',
    specialists: ['infectious-disease', 'pulmonologist'],
    prevalence: 'common'
  },

  // ============================================================================
  // SKIN CONDITIONS (Extended)
  // ============================================================================
  
  'eczema': {
    id: 'eczema',
    name: 'Eczema (Atopic Dermatitis)',
    nameAr: 'الإكزيما',
    nameDe: 'Neurodermitis',
    nameFr: 'Eczéma',
    icd11: 'EA80',
    snomed: '43116000',
    category: 'skin',
    urgency: 'routine',
    primarySymptoms: ['itching', 'rash', 'dry-skin'],
    secondarySymptoms: ['skin-redness', 'skin-cracking', 'skin-thickening'],
    associatedSymptoms: ['sleep-problems', 'skin-infection'],
    riskFactors: ['family-history-allergies', 'asthma', 'hay-fever', 'dry-climate'],
    ageGroups: ['infant', 'child', 'adolescent', 'adult'],
    genderPrevalence: 'equal',
    description: 'Eczema is a condition that makes skin red, inflamed, and itchy.',
    specialists: ['dermatologist', 'allergist'],
    prevalence: 'common',
    typicalDuration: 'chronic'
  },
  
  'psoriasis': {
    id: 'psoriasis',
    name: 'Psoriasis',
    nameAr: 'الصدفية',
    nameDe: 'Psoriasis',
    nameFr: 'Psoriasis',
    icd11: 'EA90',
    snomed: '9014002',
    category: 'skin',
    urgency: 'routine',
    primarySymptoms: ['rash-scaly', 'skin-redness', 'itching'],
    secondarySymptoms: ['dry-cracked-skin', 'burning', 'soreness'],
    associatedSymptoms: ['nail-changes', 'joint-pain', 'stiffness'],
    riskFactors: ['family-history', 'stress', 'obesity', 'smoking', 'infections'],
    ageGroups: ['adolescent', 'adult', 'elderly'],
    genderPrevalence: 'equal',
    description: 'Psoriasis is an autoimmune condition causing rapid skin cell turnover, creating scales and red patches.',
    specialists: ['dermatologist', 'rheumatologist'],
    prevalence: 'common',
    typicalDuration: 'chronic'
  },
  
  'acne': {
    id: 'acne',
    name: 'Acne Vulgaris',
    nameAr: 'حب الشباب',
    nameDe: 'Akne',
    nameFr: 'Acné',
    icd11: 'ED80',
    snomed: '11381005',
    category: 'skin',
    urgency: 'self-care',
    primarySymptoms: ['skin-bumps', 'blackheads', 'whiteheads'],
    secondarySymptoms: ['skin-redness', 'skin-pain', 'scarring'],
    associatedSymptoms: ['oily-skin', 'depression', 'anxiety'],
    riskFactors: ['hormonal-changes', 'family-history', 'stress', 'certain-medications', 'diet'],
    ageGroups: ['adolescent', 'adult'],
    genderPrevalence: 'equal',
    description: 'Acne is a skin condition where hair follicles become clogged with oil and dead skin cells.',
    specialists: ['dermatologist'],
    prevalence: 'common'
  },
  
  'cellulitis': {
    id: 'cellulitis',
    name: 'Cellulitis',
    nameAr: 'التهاب النسيج الخلوي',
    nameDe: 'Zellulitis',
    nameFr: 'Cellulite infectieuse',
    icd11: '1B70',
    snomed: '128045006',
    category: 'skin',
    urgency: 'urgent',
    primarySymptoms: ['skin-redness', 'skin-swelling', 'skin-warmth', 'pain'],
    secondarySymptoms: ['fever', 'chills', 'swollen-lymph-nodes'],
    associatedSymptoms: ['red-streaking', 'blisters', 'fatigue'],
    riskFactors: ['skin-injury', 'weakened-immunity', 'diabetes', 'obesity', 'lymphedema'],
    ageGroups: ['child', 'adolescent', 'adult', 'elderly'],
    genderPrevalence: 'equal',
    description: 'Cellulitis is a common bacterial skin infection that can spread rapidly.',
    specialists: ['dermatologist', 'infectious-disease'],
    prevalence: 'common'
  },
  
  'hives': {
    id: 'hives',
    name: 'Hives (Urticaria)',
    nameAr: 'الشرى',
    nameDe: 'Nesselsucht',
    nameFr: 'Urticaire',
    icd11: 'EB00',
    snomed: '126485001',
    category: 'skin',
    urgency: 'routine',
    primarySymptoms: ['hives', 'itching', 'skin-swelling'],
    secondarySymptoms: ['skin-redness', 'burning'],
    associatedSymptoms: ['angioedema', 'throat-tightness'],
    riskFactors: ['allergies', 'infections', 'stress', 'medications', 'foods'],
    ageGroups: ['child', 'adolescent', 'adult', 'elderly'],
    genderPrevalence: 'equal',
    description: 'Hives are raised, itchy welts that appear on the skin due to an allergic reaction.',
    specialists: ['dermatologist', 'allergist'],
    prevalence: 'common'
  },

  // ============================================================================
  // MUSCULOSKELETAL (Extended)
  // ============================================================================
  
  'gout': {
    id: 'gout',
    name: 'Gout',
    nameAr: 'النقرس',
    nameDe: 'Gicht',
    nameFr: 'Goutte',
    icd11: 'FA25',
    snomed: '90560007',
    category: 'musculoskeletal',
    urgency: 'urgent',
    primarySymptoms: ['joint-pain-severe', 'joint-swelling', 'joint-redness'],
    secondarySymptoms: ['skin-warmth', 'limited-mobility'],
    associatedSymptoms: ['fever', 'fatigue'],
    riskFactors: ['male', 'obesity', 'red-meat-diet', 'alcohol', 'hypertension', 'kidney-disease'],
    ageGroups: ['adult', 'elderly'],
    genderPrevalence: 'male',
    description: 'Gout is a form of arthritis characterized by sudden, severe attacks of pain, swelling, and redness in joints.',
    specialists: ['rheumatologist'],
    prevalence: 'common'
  },
  
  'fibromyalgia': {
    id: 'fibromyalgia',
    name: 'Fibromyalgia',
    nameAr: 'الألم العضلي الليفي',
    nameDe: 'Fibromyalgie',
    nameFr: 'Fibromyalgie',
    icd11: 'MG30.0',
    snomed: '24693007',
    category: 'musculoskeletal',
    urgency: 'routine',
    primarySymptoms: ['muscle-pain', 'fatigue', 'sleep-problems'],
    secondarySymptoms: ['headache', 'concentration-difficulty', 'mood-changes'],
    associatedSymptoms: ['numbness', 'tingling', 'irritable-bowel-symptoms', 'depression'],
    riskFactors: ['female', 'family-history', 'rheumatoid-arthritis', 'lupus', 'physical-trauma'],
    ageGroups: ['adult', 'elderly'],
    genderPrevalence: 'female',
    description: 'Fibromyalgia is a disorder characterized by widespread musculoskeletal pain and fatigue.',
    specialists: ['rheumatologist', 'pain-specialist'],
    prevalence: 'common',
    typicalDuration: 'chronic'
  },
  
  'carpal-tunnel': {
    id: 'carpal-tunnel',
    name: 'Carpal Tunnel Syndrome',
    nameAr: 'متلازمة النفق الرسغي',
    nameDe: 'Karpaltunnelsyndrom',
    nameFr: 'Syndrome du canal carpien',
    icd11: '8C10.0',
    snomed: '57406009',
    category: 'musculoskeletal',
    urgency: 'routine',
    primarySymptoms: ['hand-numbness', 'hand-tingling', 'hand-weakness'],
    secondarySymptoms: ['wrist-pain', 'finger-numbness'],
    associatedSymptoms: ['dropping-objects', 'night-symptoms'],
    riskFactors: ['repetitive-hand-use', 'pregnancy', 'diabetes', 'obesity', 'thyroid-disorders'],
    ageGroups: ['adult', 'elderly'],
    genderPrevalence: 'female',
    description: 'Carpal tunnel syndrome causes numbness and tingling in the hand due to a compressed nerve.',
    specialists: ['orthopedic', 'neurologist', 'hand-surgeon'],
    prevalence: 'common'
  },
  
  'sciatica': {
    id: 'sciatica',
    name: 'Sciatica',
    nameAr: 'عرق النسا',
    nameDe: 'Ischias',
    nameFr: 'Sciatique',
    icd11: 'ME84.2',
    snomed: '23056005',
    category: 'musculoskeletal',
    urgency: 'routine',
    primarySymptoms: ['back-pain-lower', 'leg-pain', 'numbness-limbs'],
    secondarySymptoms: ['tingling', 'muscle-weakness'],
    associatedSymptoms: ['hip-pain', 'difficulty-walking'],
    riskFactors: ['age>40', 'obesity', 'prolonged-sitting', 'diabetes', 'physical-labor'],
    ageGroups: ['adult', 'elderly'],
    genderPrevalence: 'equal',
    description: 'Sciatica is pain that radiates along the sciatic nerve, from the lower back through the hips and down the legs.',
    specialists: ['orthopedic', 'neurologist', 'physiotherapist'],
    prevalence: 'common'
  },
  
  'herniated-disc': {
    id: 'herniated-disc',
    name: 'Herniated Disc',
    nameAr: 'الانزلاق الغضروفي',
    nameDe: 'Bandscheibenvorfall',
    nameFr: 'Hernie discale',
    icd11: 'FA82.2',
    snomed: '76107001',
    category: 'musculoskeletal',
    urgency: 'routine',
    primarySymptoms: ['back-pain', 'neck-pain', 'arm-pain', 'leg-pain'],
    secondarySymptoms: ['numbness', 'tingling', 'weakness'],
    associatedSymptoms: ['muscle-spasms', 'difficulty-walking'],
    riskFactors: ['age-30-50', 'heavy-lifting', 'obesity', 'genetics', 'sedentary-lifestyle'],
    ageGroups: ['adult', 'elderly'],
    genderPrevalence: 'male',
    description: 'A herniated disc occurs when the soft center of a spinal disc pushes through a crack in the tougher exterior.',
    specialists: ['orthopedic', 'neurologist', 'spine-surgeon'],
    prevalence: 'common'
  },
  
  'tendinitis': {
    id: 'tendinitis',
    name: 'Tendinitis',
    nameAr: 'التهاب الأوتار',
    nameDe: 'Sehnenentzündung',
    nameFr: 'Tendinite',
    icd11: 'FB40',
    snomed: '34840004',
    category: 'musculoskeletal',
    urgency: 'routine',
    primarySymptoms: ['joint-pain', 'tenderness', 'swelling'],
    secondarySymptoms: ['stiffness', 'weakness'],
    associatedSymptoms: ['limited-mobility', 'grinding-sensation'],
    riskFactors: ['repetitive-motion', 'sports', 'age>40', 'poor-posture', 'sudden-activity-increase'],
    ageGroups: ['adult', 'elderly'],
    genderPrevalence: 'equal',
    description: 'Tendinitis is inflammation or irritation of a tendon, often from repetitive minor impact.',
    specialists: ['orthopedic', 'sports-medicine', 'physiotherapist'],
    prevalence: 'common'
  },

  // ============================================================================
  // UROLOGICAL/REPRODUCTIVE (Extended)
  // ============================================================================
  
  'benign-prostatic-hyperplasia': {
    id: 'benign-prostatic-hyperplasia',
    name: 'Benign Prostatic Hyperplasia (BPH)',
    nameAr: 'تضخم البروستاتا الحميد',
    nameDe: 'Benigne Prostatahyperplasie',
    nameFr: 'Hyperplasie bénigne de la prostate',
    icd11: 'GA90',
    snomed: '266569009',
    category: 'urinary',
    urgency: 'routine',
    primarySymptoms: ['frequent-urination', 'urgency-urination', 'weak-urine-stream'],
    secondarySymptoms: ['difficulty-starting-urination', 'dribbling', 'incomplete-bladder-emptying'],
    associatedSymptoms: ['nighttime-urination', 'straining'],
    riskFactors: ['age>50', 'family-history', 'obesity', 'diabetes', 'heart-disease'],
    ageGroups: ['adult', 'elderly'],
    genderPrevalence: 'male',
    description: 'BPH is an enlarged prostate gland that can cause urinary problems in older men.',
    specialists: ['urologist'],
    prevalence: 'common',
    typicalDuration: 'chronic'
  },
  
  'prostatitis': {
    id: 'prostatitis',
    name: 'Prostatitis',
    nameAr: 'التهاب البروستاتا',
    nameDe: 'Prostatitis',
    nameFr: 'Prostatite',
    icd11: 'GA91',
    snomed: '9713002',
    category: 'urinary',
    urgency: 'urgent',
    primarySymptoms: ['painful-urination', 'pelvic-pain', 'frequent-urination'],
    secondarySymptoms: ['fever', 'chills', 'difficulty-urinating'],
    associatedSymptoms: ['blood-urine', 'sexual-dysfunction', 'lower-back-pain'],
    riskFactors: ['urinary-tract-infection', 'pelvic-injury', 'prostate-biopsy', 'age-30-50'],
    ageGroups: ['adult', 'elderly'],
    genderPrevalence: 'male',
    description: 'Prostatitis is inflammation of the prostate gland, causing painful urination and pelvic pain.',
    specialists: ['urologist'],
    prevalence: 'common'
  },
  
  'erectile-dysfunction': {
    id: 'erectile-dysfunction',
    name: 'Erectile Dysfunction',
    nameAr: 'ضعف الانتصاب',
    nameDe: 'Erektile Dysfunktion',
    nameFr: 'Dysfonction érectile',
    icd11: 'HA00',
    snomed: '860914002',
    category: 'reproductive',
    urgency: 'routine',
    primarySymptoms: ['erectile-difficulty', 'reduced-sexual-desire'],
    secondarySymptoms: ['difficulty-maintaining-erection'],
    associatedSymptoms: ['anxiety', 'depression', 'relationship-issues'],
    riskFactors: ['diabetes', 'heart-disease', 'obesity', 'smoking', 'age>50', 'hypertension'],
    ageGroups: ['adult', 'elderly'],
    genderPrevalence: 'male',
    description: 'Erectile dysfunction is the inability to get or maintain an erection firm enough for sexual intercourse.',
    specialists: ['urologist', 'endocrinologist'],
    prevalence: 'common'
  },
  
  'pcos': {
    id: 'pcos',
    name: 'Polycystic Ovary Syndrome (PCOS)',
    nameAr: 'متلازمة تكيس المبايض',
    nameDe: 'Polyzystisches Ovarialsyndrom',
    nameFr: 'Syndrome des ovaires polykystiques',
    icd11: 'GA21',
    snomed: '69878008',
    category: 'reproductive',
    urgency: 'routine',
    primarySymptoms: ['irregular-periods', 'excess-hair-growth', 'acne'],
    secondarySymptoms: ['weight-gain-unexplained', 'hair-loss', 'skin-darkening'],
    associatedSymptoms: ['infertility', 'pelvic-pain', 'depression'],
    riskFactors: ['family-history', 'obesity', 'insulin-resistance'],
    ageGroups: ['adolescent', 'adult'],
    genderPrevalence: 'female',
    description: 'PCOS is a hormonal disorder causing enlarged ovaries with small cysts on the outer edges.',
    specialists: ['gynecologist', 'endocrinologist'],
    prevalence: 'common',
    typicalDuration: 'chronic'
  },
  
  'endometriosis': {
    id: 'endometriosis',
    name: 'Endometriosis',
    nameAr: 'بطانة الرحم المهاجرة',
    nameDe: 'Endometriose',
    nameFr: 'Endométriose',
    icd11: 'GA10',
    snomed: '129103003',
    category: 'reproductive',
    urgency: 'routine',
    primarySymptoms: ['pelvic-pain', 'painful-periods', 'pain-during-intercourse'],
    secondarySymptoms: ['heavy-periods', 'infertility', 'painful-urination'],
    associatedSymptoms: ['fatigue', 'diarrhea', 'constipation', 'bloating', 'nausea'],
    riskFactors: ['family-history', 'never-given-birth', 'short-menstrual-cycles', 'heavy-periods'],
    ageGroups: ['adolescent', 'adult'],
    genderPrevalence: 'female',
    description: 'Endometriosis is a condition where tissue similar to the uterine lining grows outside the uterus.',
    specialists: ['gynecologist'],
    prevalence: 'common',
    typicalDuration: 'chronic'
  },
  
  'yeast-infection': {
    id: 'yeast-infection',
    name: 'Vaginal Yeast Infection',
    nameAr: 'عدوى فطرية مهبلية',
    nameDe: 'Vaginale Pilzinfektion',
    nameFr: 'Infection vaginale à levures',
    icd11: '1F23.0',
    snomed: '78048006',
    category: 'reproductive',
    urgency: 'routine',
    primarySymptoms: ['vaginal-itching', 'vaginal-discharge', 'burning-urination'],
    secondarySymptoms: ['redness', 'swelling', 'pain-during-intercourse'],
    associatedSymptoms: ['soreness', 'rash'],
    riskFactors: ['antibiotics', 'pregnancy', 'diabetes', 'weakened-immunity', 'hormonal-contraceptives'],
    ageGroups: ['adolescent', 'adult', 'elderly'],
    genderPrevalence: 'female',
    description: 'A vaginal yeast infection is a fungal infection that causes irritation, discharge, and intense itchiness.',
    specialists: ['gynecologist'],
    prevalence: 'common'
  },

  // ============================================================================
  // MENTAL HEALTH (Extended)
  // ============================================================================
  
  'panic-disorder': {
    id: 'panic-disorder',
    name: 'Panic Disorder',
    nameAr: 'اضطراب الهلع',
    nameDe: 'Panikstörung',
    nameFr: 'Trouble panique',
    icd11: '6B01',
    snomed: '371631005',
    category: 'mental',
    urgency: 'routine',
    primarySymptoms: ['panic-attack', 'rapid-heartbeat', 'shortness-breath', 'chest-pain'],
    secondarySymptoms: ['trembling', 'sweating', 'dizziness', 'nausea'],
    associatedSymptoms: ['fear-of-dying', 'numbness', 'chills', 'hot-flashes'],
    riskFactors: ['family-history', 'major-stress', 'trauma', 'smoking', 'excessive-caffeine'],
    ageGroups: ['adolescent', 'adult'],
    genderPrevalence: 'female',
    description: 'Panic disorder involves repeated, unexpected panic attacks and persistent fear of future attacks.',
    specialists: ['psychiatrist', 'psychologist'],
    prevalence: 'common',
    differentialDiagnosis: ['heart-attack', 'hyperthyroidism', 'asthma']
  },
  
  'ptsd': {
    id: 'ptsd',
    name: 'Post-Traumatic Stress Disorder',
    nameAr: 'اضطراب ما بعد الصدمة',
    nameDe: 'Posttraumatische Belastungsstörung',
    nameFr: 'Trouble de stress post-traumatique',
    icd11: '6B40',
    snomed: '47505003',
    category: 'mental',
    urgency: 'routine',
    primarySymptoms: ['flashbacks', 'nightmares', 'anxiety-severe', 'avoidance'],
    secondarySymptoms: ['insomnia', 'irritability', 'hypervigilance'],
    associatedSymptoms: ['depression', 'guilt', 'concentration-difficulty', 'emotional-numbness'],
    riskFactors: ['trauma-exposure', 'previous-mental-illness', 'lack-of-support', 'childhood-abuse'],
    ageGroups: ['child', 'adolescent', 'adult', 'elderly'],
    genderPrevalence: 'female',
    description: 'PTSD is a mental health condition triggered by experiencing or witnessing a terrifying event.',
    specialists: ['psychiatrist', 'psychologist'],
    prevalence: 'common',
    typicalDuration: 'chronic'
  },
  
  'ocd': {
    id: 'ocd',
    name: 'Obsessive-Compulsive Disorder',
    nameAr: 'الوسواس القهري',
    nameDe: 'Zwangsstörung',
    nameFr: 'Trouble obsessionnel-compulsif',
    icd11: '6B20',
    snomed: '191736004',
    category: 'mental',
    urgency: 'routine',
    primarySymptoms: ['obsessive-thoughts', 'compulsive-behaviors', 'anxiety'],
    secondarySymptoms: ['distress', 'time-consuming-rituals'],
    associatedSymptoms: ['depression', 'avoidance', 'difficulty-functioning'],
    riskFactors: ['family-history', 'trauma', 'other-mental-disorders'],
    ageGroups: ['child', 'adolescent', 'adult'],
    genderPrevalence: 'equal',
    description: 'OCD features a pattern of unwanted thoughts and fears that lead to repetitive behaviors.',
    specialists: ['psychiatrist', 'psychologist'],
    prevalence: 'common',
    typicalDuration: 'chronic'
  },
  
  'bipolar-disorder': {
    id: 'bipolar-disorder',
    name: 'Bipolar Disorder',
    nameAr: 'اضطراب ثنائي القطب',
    nameDe: 'Bipolare Störung',
    nameFr: 'Trouble bipolaire',
    icd11: '6A60',
    snomed: '13746004',
    category: 'mental',
    urgency: 'routine',
    primarySymptoms: ['mood-swings', 'mania', 'depression'],
    secondarySymptoms: ['insomnia', 'racing-thoughts', 'impulsivity', 'irritability'],
    associatedSymptoms: ['fatigue', 'concentration-difficulty', 'suicidal-thoughts'],
    riskFactors: ['family-history', 'high-stress', 'drug-abuse', 'traumatic-event'],
    ageGroups: ['adolescent', 'adult'],
    genderPrevalence: 'equal',
    description: 'Bipolar disorder causes extreme mood swings between emotional highs (mania) and lows (depression).',
    specialists: ['psychiatrist'],
    prevalence: 'uncommon',
    typicalDuration: 'chronic',
    crisis: true
  },
  
  'adhd': {
    id: 'adhd',
    name: 'Attention Deficit Hyperactivity Disorder',
    nameAr: 'اضطراب فرط الحركة ونقص الانتباه',
    nameDe: 'ADHS',
    nameFr: 'TDAH',
    icd11: '6A05',
    snomed: '406506008',
    category: 'mental',
    urgency: 'routine',
    primarySymptoms: ['inattention', 'hyperactivity', 'impulsivity'],
    secondarySymptoms: ['disorganization', 'forgetfulness', 'difficulty-following-instructions'],
    associatedSymptoms: ['restlessness', 'difficulty-waiting', 'interrupting'],
    riskFactors: ['family-history', 'premature-birth', 'low-birth-weight', 'prenatal-exposure'],
    ageGroups: ['child', 'adolescent', 'adult'],
    genderPrevalence: 'male',
    description: 'ADHD is a chronic condition including attention difficulty, hyperactivity, and impulsiveness.',
    specialists: ['psychiatrist', 'psychologist', 'neurologist'],
    prevalence: 'common',
    typicalDuration: 'chronic'
  },
  
  'eating-disorder-anorexia': {
    id: 'eating-disorder-anorexia',
    name: 'Anorexia Nervosa',
    nameAr: 'فقدان الشهية العصبي',
    nameDe: 'Magersucht',
    nameFr: 'Anorexie mentale',
    icd11: '6B80',
    snomed: '56882008',
    category: 'mental',
    urgency: 'urgent',
    primarySymptoms: ['weight-loss-severe', 'fear-of-gaining-weight', 'distorted-body-image'],
    secondarySymptoms: ['fatigue', 'dizziness', 'hair-loss', 'irregular-periods'],
    associatedSymptoms: ['depression', 'anxiety', 'cold-intolerance', 'constipation'],
    riskFactors: ['female', 'adolescent', 'family-history', 'perfectionism', 'trauma'],
    ageGroups: ['adolescent', 'adult'],
    genderPrevalence: 'female',
    description: 'Anorexia nervosa is an eating disorder characterized by low weight, fear of gaining weight, and a distorted body image.',
    specialists: ['psychiatrist', 'psychologist', 'nutritionist'],
    prevalence: 'uncommon',
    crisis: true
  },

  // ============================================================================
  // AUTOIMMUNE CONDITIONS
  // ============================================================================
  
  'lupus': {
    id: 'lupus',
    name: 'Systemic Lupus Erythematosus',
    nameAr: 'الذئبة الحمراء',
    nameDe: 'Systemischer Lupus erythematodes',
    nameFr: 'Lupus érythémateux systémique',
    icd11: '4A40',
    snomed: '55464009',
    category: 'autoimmune',
    urgency: 'routine',
    primarySymptoms: ['fatigue', 'joint-pain', 'skin-rash'],
    secondarySymptoms: ['fever', 'sun-sensitivity', 'hair-loss'],
    associatedSymptoms: ['mouth-ulcers', 'kidney-problems', 'chest-pain', 'cognitive-issues'],
    riskFactors: ['female', 'age-15-45', 'african-american', 'family-history'],
    ageGroups: ['adolescent', 'adult'],
    genderPrevalence: 'female',
    description: 'Lupus is a chronic autoimmune disease where the immune system attacks healthy tissue.',
    specialists: ['rheumatologist'],
    prevalence: 'uncommon',
    typicalDuration: 'chronic'
  },
  
  'sjogrens-syndrome': {
    id: 'sjogrens-syndrome',
    name: 'Sjögren\'s Syndrome',
    nameAr: 'متلازمة شوغرن',
    nameDe: 'Sjögren-Syndrom',
    nameFr: 'Syndrome de Sjögren',
    icd11: '4A42',
    snomed: '83901003',
    category: 'autoimmune',
    urgency: 'routine',
    primarySymptoms: ['dry-eyes', 'dry-mouth', 'fatigue'],
    secondarySymptoms: ['joint-pain', 'swollen-glands', 'skin-dryness'],
    associatedSymptoms: ['difficulty-swallowing', 'dental-cavities', 'vaginal-dryness'],
    riskFactors: ['female', 'age>40', 'rheumatic-disease'],
    ageGroups: ['adult', 'elderly'],
    genderPrevalence: 'female',
    description: 'Sjögren\'s syndrome is an autoimmune disorder characterized by dry eyes and dry mouth.',
    specialists: ['rheumatologist', 'ophthalmologist'],
    prevalence: 'uncommon',
    typicalDuration: 'chronic'
  },
  
  'hashimotos': {
    id: 'hashimotos',
    name: 'Hashimoto\'s Thyroiditis',
    nameAr: 'التهاب الغدة الدرقية هاشيموتو',
    nameDe: 'Hashimoto-Thyreoiditis',
    nameFr: 'Thyroïdite de Hashimoto',
    icd11: '5A00.10',
    snomed: '21983002',
    category: 'autoimmune',
    urgency: 'routine',
    primarySymptoms: ['fatigue', 'weight-gain-unexplained', 'cold-intolerance'],
    secondarySymptoms: ['constipation', 'dry-skin', 'hair-loss'],
    associatedSymptoms: ['depression', 'muscle-weakness', 'joint-pain', 'memory-problems'],
    riskFactors: ['female', 'family-history', 'other-autoimmune-conditions'],
    ageGroups: ['adult', 'elderly'],
    genderPrevalence: 'female',
    description: 'Hashimoto\'s is an autoimmune condition where the immune system attacks the thyroid.',
    specialists: ['endocrinologist'],
    prevalence: 'common',
    typicalDuration: 'chronic'
  }
}

// Combine with main database
export const getAllExtendedConditions = () => EXTENDED_CONDITIONS

export const getExtendedConditionCount = () => Object.keys(EXTENDED_CONDITIONS).length

console.log(`MediSense AI Pro™ Extended Database loaded with ${getExtendedConditionCount()} additional conditions`)
