/**
 * SelectCareOS™ Documentation Portal
 * Professional PDF Documents - MVP Specification & Functional Specification
 * 
 * Generated by: Dr. Sherif Akram Metwalli, M.Sc.
 * Powered by: German Select Medical Tourism
 * 
 * Features:
 * - Professional PDF download links
 * - Print-optimized layouts
 * - Executive branding
 * - Multiple document formats
 */

import { bottomNavStyles, getUnifiedBottomNav } from '../components/bottom-nav';

// Document metadata
const DOCUMENT_INFO = {
  author: 'Dr. Sherif Akram Metwalli, M.Sc.',
  company: 'German Select Medical Tourism',
  version: '1.0',
  date: new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' }),
  copyright: `© ${new Date().getFullYear()} German Select. All Rights Reserved.`
};

// Document list
const DOCUMENTS = [
  {
    id: 'mvp-specification',
    title: 'MVP Specification Document',
    subtitle: 'Complete Technical & Functional Specification',
    version: 'v1.0',
    pages: '94+',
    icon: 'file-alt',
    color: '#001F3F',
    description: 'Comprehensive MVP specification including Executive Summary, Platform Analysis, Functional Specification (FSD), Technical Specification (TSD), Development Roadmap, and Developer Handoff Package.',
    sections: [
      'Executive Summary & Vision',
      'Platform Analysis - Current State',
      'Functional Specification Document (FSD)',
      'Technical Specification Document (TSD)',
      'MVP Development Roadmap',
      'Developer Handoff Package'
    ],
    downloadUrl: '/api/docs/mvp-specification/pdf',
    viewUrl: '/docs/mvp-specification'
  },
  {
    id: 'functional-specification',
    title: 'Functional Specification Document',
    subtitle: 'FSD - User Stories & Requirements',
    version: 'v1.0',
    pages: '45+',
    icon: 'clipboard-list',
    color: '#D4A843',
    description: 'Detailed functional requirements including user personas, use cases, feature specifications, user interface requirements, and acceptance criteria.',
    sections: [
      'User Personas & Journeys',
      'Telemedicine Features',
      'Booking System Requirements',
      'Therapeutic Retreat Booking',
      'User Management & RBAC',
      'E-Commerce & Payments'
    ],
    downloadUrl: '/api/docs/functional-specification/pdf',
    viewUrl: '/docs/functional-specification'
  },
  {
    id: 'technical-specification',
    title: 'Technical Specification Document',
    subtitle: 'TSD - Architecture & Implementation',
    version: 'v1.0',
    pages: '35+',
    icon: 'code',
    color: '#3B82F6',
    description: 'Technical architecture, database schemas, API specifications, security requirements, infrastructure design, and deployment guidelines.',
    sections: [
      'System Architecture',
      'Database Design',
      'API Specifications',
      'Security & Compliance',
      'Infrastructure & DevOps',
      'Integration Patterns'
    ],
    downloadUrl: '/api/docs/technical-specification/pdf',
    viewUrl: '/docs/technical-specification'
  },
  {
    id: 'development-roadmap',
    title: 'MVP Development Roadmap',
    subtitle: 'Phase-by-Phase Implementation Plan',
    version: 'v1.0',
    pages: '20+',
    icon: 'road',
    color: '#22C55E',
    description: 'Detailed 12-month development roadmap with sprint planning, milestones, resource allocation, risk mitigation, and success metrics.',
    sections: [
      'Phase 1: Foundation (Months 1-4)',
      'Phase 2: Enhancement (Months 5-8)',
      'Phase 3: Scale (Months 9-12)',
      'Sprint Planning & Milestones',
      'Risk Assessment & Mitigation',
      'Success Metrics & KPIs'
    ],
    downloadUrl: '/api/docs/development-roadmap/pdf',
    viewUrl: '/docs/development-roadmap'
  }
];

export function documentationPortalPage(): string {
  const documentCards = DOCUMENTS.map(doc => `
    <div class="doc-card" style="border-left: 4px solid ${doc.color};">
      <div class="doc-header">
        <div class="doc-icon" style="background: ${doc.color};">
          <i class="fas fa-${doc.icon}"></i>
        </div>
        <div class="doc-meta">
          <span class="doc-version">${doc.version}</span>
          <span class="doc-pages">${doc.pages} Pages</span>
        </div>
      </div>
      
      <h3 class="doc-title">${doc.title}</h3>
      <p class="doc-subtitle">${doc.subtitle}</p>
      <p class="doc-description">${doc.description}</p>
      
      <div class="doc-sections">
        <h4>Contents:</h4>
        <ul>
          ${doc.sections.map(s => `<li><i class="fas fa-check"></i> ${s}</li>`).join('')}
        </ul>
      </div>
      
      <div class="doc-actions">
        <a href="${doc.viewUrl}" class="btn-view">
          <i class="fas fa-eye"></i> View Document
        </a>
        <a href="${doc.downloadUrl}" class="btn-download" style="background: ${doc.color};">
          <i class="fas fa-download"></i> Download PDF
        </a>
      </div>
    </div>
  `).join('');

  return `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Documentation Portal - SelectCareOS™</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@6.4.0/css/all.min.css" rel="stylesheet">
    <style>
        :root {
            --navy: #001F3F;
            --navy-light: #003366;
            --gold: #D4A843;
            --gold-light: #F5E6C0;
            --cream: #FDFBF7;
        }
        
        * {
            font-family: 'Inter', -apple-system, BlinkMacSystemFont, sans-serif;
            box-sizing: border-box;
        }
        
        body {
            background: linear-gradient(180deg, var(--cream) 0%, #F5F0E6 100%);
            color: var(--navy);
            min-height: 100vh;
            padding-bottom: 140px;
        }
        
        /* Hero Section */
        .hero {
            background: linear-gradient(135deg, var(--navy) 0%, var(--navy-light) 100%);
            padding: 60px 20px 80px;
            text-align: center;
            position: relative;
            overflow: hidden;
        }
        
        .hero::before {
            content: '';
            position: absolute;
            top: -50%;
            right: -20%;
            width: 80%;
            height: 200%;
            background: radial-gradient(ellipse at center, rgba(212, 168, 67, 0.1) 0%, transparent 70%);
            pointer-events: none;
        }
        
        .hero-badge {
            display: inline-flex;
            align-items: center;
            gap: 8px;
            background: rgba(212, 168, 67, 0.15);
            border: 1px solid rgba(212, 168, 67, 0.3);
            padding: 8px 16px;
            border-radius: 30px;
            color: var(--gold);
            font-size: 12px;
            font-weight: 600;
            margin-bottom: 20px;
            text-transform: uppercase;
            letter-spacing: 1px;
        }
        
        .hero h1 {
            color: white;
            font-size: 36px;
            font-weight: 800;
            margin-bottom: 12px;
        }
        
        .hero h1 span {
            color: var(--gold);
        }
        
        .hero p {
            color: rgba(255, 255, 255, 0.8);
            font-size: 16px;
            max-width: 600px;
            margin: 0 auto 24px;
        }
        
        .author-info {
            display: flex;
            align-items: center;
            justify-content: center;
            gap: 16px;
            flex-wrap: wrap;
            color: rgba(255, 255, 255, 0.7);
            font-size: 13px;
        }
        
        .author-info .divider {
            width: 1px;
            height: 20px;
            background: rgba(255, 255, 255, 0.3);
        }
        
        .author-info strong {
            color: var(--gold);
        }
        
        /* Document Grid */
        .docs-container {
            max-width: 1200px;
            margin: -40px auto 0;
            padding: 0 20px;
            position: relative;
            z-index: 10;
        }
        
        .docs-grid {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(320px, 1fr));
            gap: 24px;
        }
        
        /* Document Card */
        .doc-card {
            background: white;
            border-radius: 16px;
            padding: 24px;
            box-shadow: 0 4px 20px rgba(0, 31, 63, 0.08);
            transition: all 0.3s ease;
        }
        
        .doc-card:hover {
            transform: translateY(-4px);
            box-shadow: 0 12px 40px rgba(0, 31, 63, 0.12);
        }
        
        .doc-header {
            display: flex;
            justify-content: space-between;
            align-items: flex-start;
            margin-bottom: 16px;
        }
        
        .doc-icon {
            width: 48px;
            height: 48px;
            border-radius: 12px;
            display: flex;
            align-items: center;
            justify-content: center;
            color: white;
            font-size: 20px;
        }
        
        .doc-meta {
            display: flex;
            flex-direction: column;
            align-items: flex-end;
            gap: 4px;
        }
        
        .doc-version {
            background: var(--gold-light);
            color: var(--navy);
            padding: 4px 10px;
            border-radius: 12px;
            font-size: 11px;
            font-weight: 700;
        }
        
        .doc-pages {
            color: #6B7280;
            font-size: 11px;
        }
        
        .doc-title {
            font-size: 18px;
            font-weight: 700;
            color: var(--navy);
            margin-bottom: 4px;
        }
        
        .doc-subtitle {
            font-size: 13px;
            color: var(--gold);
            font-weight: 600;
            margin-bottom: 12px;
        }
        
        .doc-description {
            font-size: 13px;
            color: #6B7280;
            line-height: 1.6;
            margin-bottom: 16px;
        }
        
        .doc-sections {
            background: #F9FAFB;
            border-radius: 12px;
            padding: 16px;
            margin-bottom: 20px;
        }
        
        .doc-sections h4 {
            font-size: 12px;
            font-weight: 700;
            color: var(--navy);
            margin-bottom: 10px;
            text-transform: uppercase;
            letter-spacing: 0.5px;
        }
        
        .doc-sections ul {
            list-style: none;
            padding: 0;
            margin: 0;
        }
        
        .doc-sections li {
            display: flex;
            align-items: center;
            gap: 8px;
            font-size: 12px;
            color: #4B5563;
            padding: 4px 0;
        }
        
        .doc-sections li i {
            color: #22C55E;
            font-size: 10px;
        }
        
        .doc-actions {
            display: flex;
            gap: 12px;
        }
        
        .btn-view, .btn-download {
            flex: 1;
            display: flex;
            align-items: center;
            justify-content: center;
            gap: 8px;
            padding: 12px 16px;
            border-radius: 10px;
            font-size: 13px;
            font-weight: 600;
            text-decoration: none;
            transition: all 0.2s ease;
        }
        
        .btn-view {
            background: #F3F4F6;
            color: var(--navy);
        }
        
        .btn-view:hover {
            background: #E5E7EB;
        }
        
        .btn-download {
            color: white;
        }
        
        .btn-download:hover {
            opacity: 0.9;
            transform: translateY(-1px);
        }
        
        /* Footer Info */
        .footer-info {
            max-width: 1200px;
            margin: 40px auto;
            padding: 0 20px;
        }
        
        .info-card {
            background: linear-gradient(135deg, var(--navy) 0%, var(--navy-light) 100%);
            border-radius: 16px;
            padding: 32px;
            color: white;
            display: flex;
            align-items: center;
            gap: 24px;
            flex-wrap: wrap;
        }
        
        .info-card .logo {
            font-size: 24px;
            font-weight: 800;
        }
        
        .info-card .logo span {
            color: var(--gold);
        }
        
        .info-card .details {
            flex: 1;
            min-width: 200px;
        }
        
        .info-card .details p {
            margin: 0;
            color: rgba(255, 255, 255, 0.8);
            font-size: 13px;
            line-height: 1.6;
        }
        
        .info-card .contact {
            display: flex;
            gap: 12px;
        }
        
        .info-card .contact a {
            width: 40px;
            height: 40px;
            background: rgba(255, 255, 255, 0.1);
            border-radius: 50%;
            display: flex;
            align-items: center;
            justify-content: center;
            color: white;
            text-decoration: none;
            transition: all 0.2s ease;
        }
        
        .info-card .contact a:hover {
            background: var(--gold);
            color: var(--navy);
        }
        
        /* Responsive */
        @media (max-width: 640px) {
            .hero {
                padding: 40px 16px 60px;
            }
            
            .hero h1 {
                font-size: 28px;
            }
            
            .docs-grid {
                grid-template-columns: 1fr;
            }
            
            .doc-actions {
                flex-direction: column;
            }
            
            .info-card {
                flex-direction: column;
                text-align: center;
            }
        }
        
        ${bottomNavStyles}
    </style>
</head>
<body>
    <!-- Hero Section -->
    <header class="hero">
        <div class="hero-badge">
            <i class="fas fa-file-alt"></i>
            Documentation Portal
        </div>
        <h1>SelectCare<span>OS</span>™ Documentation</h1>
        <p>Professional specification documents for the German Select Medical Tourism Platform. Download comprehensive PDFs for development, stakeholders, and investors.</p>
        <div class="author-info">
            <span><i class="fas fa-user-md"></i> Generated by <strong>${DOCUMENT_INFO.author}</strong></span>
            <span class="divider"></span>
            <span><i class="fas fa-building"></i> Powered by <strong>${DOCUMENT_INFO.company}</strong></span>
            <span class="divider"></span>
            <span><i class="fas fa-calendar"></i> ${DOCUMENT_INFO.date}</span>
        </div>
    </header>
    
    <!-- Documents Grid -->
    <main class="docs-container">
        <div class="docs-grid">
            ${documentCards}
        </div>
    </main>
    
    <!-- Footer Info -->
    <div class="footer-info">
        <div class="info-card">
            <div class="logo">
                SelectCare<span>OS</span>™
            </div>
            <div class="details">
                <p>
                    <strong>German Medical Excellence, Red Sea Recovery</strong><br>
                    ${DOCUMENT_INFO.copyright}<br>
                    All documents are confidential and intended for authorized personnel only.
                </p>
            </div>
            <div class="contact">
                <a href="https://germanselect.org" target="_blank" title="Website">
                    <i class="fas fa-globe"></i>
                </a>
                <a href="mailto:info@germanselect.org" title="Email">
                    <i class="fas fa-envelope"></i>
                </a>
                <a href="https://linkedin.com/company/germanselect" target="_blank" title="LinkedIn">
                    <i class="fab fa-linkedin-in"></i>
                </a>
            </div>
        </div>
    </div>
    
    ${getUnifiedBottomNav('none')}
</body>
</html>`;
}

// Individual document view page
export function documentViewPage(docType: string): string {
  const doc = DOCUMENTS.find(d => d.id === docType);
  if (!doc) {
    return `<html><body><h1>Document not found</h1></body></html>`;
  }
  
  return `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>${doc.title} - SelectCareOS™</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@6.4.0/css/all.min.css" rel="stylesheet">
    <style>
        :root {
            --navy: #001F3F;
            --gold: #D4A843;
            --cream: #FDFBF7;
        }
        * { font-family: 'Inter', sans-serif; box-sizing: border-box; }
        body { background: var(--cream); color: var(--navy); padding: 20px; }
        .container { max-width: 900px; margin: 0 auto; }
        .header { 
            background: var(--navy); 
            color: white; 
            padding: 40px; 
            border-radius: 16px; 
            margin-bottom: 30px;
            text-align: center;
        }
        .header h1 { font-size: 28px; margin-bottom: 8px; }
        .header h1 span { color: var(--gold); }
        .header p { opacity: 0.8; }
        .actions {
            display: flex;
            gap: 12px;
            justify-content: center;
            margin-top: 20px;
        }
        .btn {
            display: inline-flex;
            align-items: center;
            gap: 8px;
            padding: 12px 24px;
            border-radius: 8px;
            font-weight: 600;
            text-decoration: none;
            transition: all 0.2s;
        }
        .btn-primary { background: var(--gold); color: var(--navy); }
        .btn-secondary { background: rgba(255,255,255,0.1); color: white; border: 1px solid rgba(255,255,255,0.2); }
        .btn:hover { transform: translateY(-2px); }
        .content {
            background: white;
            padding: 40px;
            border-radius: 16px;
            box-shadow: 0 4px 20px rgba(0,31,63,0.08);
        }
        .loading {
            text-align: center;
            padding: 60px;
            color: #6B7280;
        }
        .loading i { font-size: 48px; margin-bottom: 16px; animation: spin 1s linear infinite; }
        @keyframes spin { to { transform: rotate(360deg); } }
        
        @media print {
            .header { break-after: page; }
            .actions { display: none; }
            body { background: white; padding: 0; }
            .content { box-shadow: none; padding: 20px; }
        }
        
        ${bottomNavStyles}
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>SelectCare<span>OS</span>™</h1>
            <h2 style="font-size: 20px; color: var(--gold); margin: 12px 0;">${doc.title}</h2>
            <p>${doc.subtitle}</p>
            <div class="actions">
                <a href="${doc.downloadUrl}" class="btn btn-primary">
                    <i class="fas fa-download"></i> Download PDF
                </a>
                <button onclick="window.print()" class="btn btn-secondary">
                    <i class="fas fa-print"></i> Print
                </button>
                <a href="/documentation" class="btn btn-secondary">
                    <i class="fas fa-arrow-left"></i> Back
                </a>
            </div>
        </div>
        
        <div class="content" id="doc-content">
            <div class="loading">
                <i class="fas fa-spinner"></i>
                <p>Loading document...</p>
            </div>
        </div>
    </div>
    
    <script>
        // Load markdown content and render
        fetch('/api/docs/${docType}/content')
            .then(res => res.text())
            .then(content => {
                document.getElementById('doc-content').innerHTML = content;
            })
            .catch(err => {
                document.getElementById('doc-content').innerHTML = 
                    '<p style="color: red;">Error loading document. Please try again.</p>';
            });
    </script>
    
    ${getUnifiedBottomNav('none')}
</body>
</html>`;
}
